/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309EditProductRequestBodySubscribeInfoEdit type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309EditProductRequestBodySubscribeInfoEdit{}

// Product202309EditProductRequestBodySubscribeInfoEdit struct for Product202309EditProductRequestBodySubscribeInfoEdit
type Product202309EditProductRequestBodySubscribeInfoEdit struct {
    // All of the Save and Subscribe discount details.
    DiscountDetails []Product202309EditProductRequestBodySubscribeInfoEditDiscountDetails `json:"discount_details,omitempty"`
    // An enum outlining whether the given product has an active Subscribe and Save promotion: - ENABLED - NOT_ENABLED  This field is required if the subscription is being created or modified.
    SubscribeStatus *string `json:"subscribe_status,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202309EditProductRequestBodySubscribeInfoEdit Product202309EditProductRequestBodySubscribeInfoEdit

// NewProduct202309EditProductRequestBodySubscribeInfoEdit instantiates a new Product202309EditProductRequestBodySubscribeInfoEdit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309EditProductRequestBodySubscribeInfoEdit() *Product202309EditProductRequestBodySubscribeInfoEdit {
    this := Product202309EditProductRequestBodySubscribeInfoEdit{}
    return &this
}

// NewProduct202309EditProductRequestBodySubscribeInfoEditWithDefaults instantiates a new Product202309EditProductRequestBodySubscribeInfoEdit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309EditProductRequestBodySubscribeInfoEditWithDefaults() *Product202309EditProductRequestBodySubscribeInfoEdit {
    this := Product202309EditProductRequestBodySubscribeInfoEdit{}
    return &this
}

// GetDiscountDetails returns the DiscountDetails field value if set, zero value otherwise.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) GetDiscountDetails() []Product202309EditProductRequestBodySubscribeInfoEditDiscountDetails {
    if o == nil || utils.IsNil(o.DiscountDetails) {
        var ret []Product202309EditProductRequestBodySubscribeInfoEditDiscountDetails
        return ret
    }
    return o.DiscountDetails
}

// GetDiscountDetailsOk returns a tuple with the DiscountDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) GetDiscountDetailsOk() ([]Product202309EditProductRequestBodySubscribeInfoEditDiscountDetails, bool) {
    if o == nil || utils.IsNil(o.DiscountDetails) {
        return nil, false
    }
    return o.DiscountDetails, true
}

// HasDiscountDetails returns a boolean if a field has been set.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) HasDiscountDetails() bool {
    if o != nil && !utils.IsNil(o.DiscountDetails) {
        return true
    }

    return false
}

// SetDiscountDetails gets a reference to the given []Product202309EditProductRequestBodySubscribeInfoEditDiscountDetails and assigns it to the DiscountDetails field.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) SetDiscountDetails(v []Product202309EditProductRequestBodySubscribeInfoEditDiscountDetails) {
    o.DiscountDetails = v
}

// GetSubscribeStatus returns the SubscribeStatus field value if set, zero value otherwise.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) GetSubscribeStatus() string {
    if o == nil || utils.IsNil(o.SubscribeStatus) {
        var ret string
        return ret
    }
    return *o.SubscribeStatus
}

// GetSubscribeStatusOk returns a tuple with the SubscribeStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) GetSubscribeStatusOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SubscribeStatus) {
        return nil, false
    }
    return o.SubscribeStatus, true
}

// HasSubscribeStatus returns a boolean if a field has been set.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) HasSubscribeStatus() bool {
    if o != nil && !utils.IsNil(o.SubscribeStatus) {
        return true
    }

    return false
}

// SetSubscribeStatus gets a reference to the given string and assigns it to the SubscribeStatus field.
func (o *Product202309EditProductRequestBodySubscribeInfoEdit) SetSubscribeStatus(v string) {
    o.SubscribeStatus = &v
}

func (o Product202309EditProductRequestBodySubscribeInfoEdit) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309EditProductRequestBodySubscribeInfoEdit) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.DiscountDetails) {
        toSerialize["discount_details"] = o.DiscountDetails
    }
    if !utils.IsNil(o.SubscribeStatus) {
        toSerialize["subscribe_status"] = o.SubscribeStatus
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202309EditProductRequestBodySubscribeInfoEdit) UnmarshalJSON(data []byte) (err error) {
    varProduct202309EditProductRequestBodySubscribeInfoEdit := _Product202309EditProductRequestBodySubscribeInfoEdit{}

    err = json.Unmarshal(data, &varProduct202309EditProductRequestBodySubscribeInfoEdit)

    if err != nil {
        return err
    }

    *o = Product202309EditProductRequestBodySubscribeInfoEdit(varProduct202309EditProductRequestBodySubscribeInfoEdit)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "discount_details")
        delete(additionalProperties, "subscribe_status")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202309EditProductRequestBodySubscribeInfoEdit struct {
	value *Product202309EditProductRequestBodySubscribeInfoEdit
	isSet bool
}

func (v NullableProduct202309EditProductRequestBodySubscribeInfoEdit) Get() *Product202309EditProductRequestBodySubscribeInfoEdit {
	return v.value
}

func (v *NullableProduct202309EditProductRequestBodySubscribeInfoEdit) Set(val *Product202309EditProductRequestBodySubscribeInfoEdit) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309EditProductRequestBodySubscribeInfoEdit) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309EditProductRequestBodySubscribeInfoEdit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309EditProductRequestBodySubscribeInfoEdit(val *Product202309EditProductRequestBodySubscribeInfoEdit) *NullableProduct202309EditProductRequestBodySubscribeInfoEdit {
	return &NullableProduct202309EditProductRequestBodySubscribeInfoEdit{value: val, isSet: true}
}

func (v NullableProduct202309EditProductRequestBodySubscribeInfoEdit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309EditProductRequestBodySubscribeInfoEdit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


