/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309GetAttributesResponseDataAttributesValues type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309GetAttributesResponseDataAttributesValues{}

// Product202309GetAttributesResponseDataAttributesValues struct for Product202309GetAttributesResponseDataAttributesValues
type Product202309GetAttributesResponseDataAttributesValues struct {
    // The icon url value of the built-in attribute value.
    IconUrl *string `json:"icon_url,omitempty"`
    // The ID of the built-in attribute value.
    Id *string `json:"id,omitempty"`
    // The name of the built-in attribute value.
    Name *string `json:"name,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202309GetAttributesResponseDataAttributesValues Product202309GetAttributesResponseDataAttributesValues

// NewProduct202309GetAttributesResponseDataAttributesValues instantiates a new Product202309GetAttributesResponseDataAttributesValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309GetAttributesResponseDataAttributesValues() *Product202309GetAttributesResponseDataAttributesValues {
    this := Product202309GetAttributesResponseDataAttributesValues{}
    return &this
}

// NewProduct202309GetAttributesResponseDataAttributesValuesWithDefaults instantiates a new Product202309GetAttributesResponseDataAttributesValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309GetAttributesResponseDataAttributesValuesWithDefaults() *Product202309GetAttributesResponseDataAttributesValues {
    this := Product202309GetAttributesResponseDataAttributesValues{}
    return &this
}

// GetIconUrl returns the IconUrl field value if set, zero value otherwise.
func (o *Product202309GetAttributesResponseDataAttributesValues) GetIconUrl() string {
    if o == nil || utils.IsNil(o.IconUrl) {
        var ret string
        return ret
    }
    return *o.IconUrl
}

// GetIconUrlOk returns a tuple with the IconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetAttributesResponseDataAttributesValues) GetIconUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.IconUrl) {
        return nil, false
    }
    return o.IconUrl, true
}

// HasIconUrl returns a boolean if a field has been set.
func (o *Product202309GetAttributesResponseDataAttributesValues) HasIconUrl() bool {
    if o != nil && !utils.IsNil(o.IconUrl) {
        return true
    }

    return false
}

// SetIconUrl gets a reference to the given string and assigns it to the IconUrl field.
func (o *Product202309GetAttributesResponseDataAttributesValues) SetIconUrl(v string) {
    o.IconUrl = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309GetAttributesResponseDataAttributesValues) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetAttributesResponseDataAttributesValues) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309GetAttributesResponseDataAttributesValues) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309GetAttributesResponseDataAttributesValues) SetId(v string) {
    o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Product202309GetAttributesResponseDataAttributesValues) GetName() string {
    if o == nil || utils.IsNil(o.Name) {
        var ret string
        return ret
    }
    return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetAttributesResponseDataAttributesValues) GetNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Name) {
        return nil, false
    }
    return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Product202309GetAttributesResponseDataAttributesValues) HasName() bool {
    if o != nil && !utils.IsNil(o.Name) {
        return true
    }

    return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Product202309GetAttributesResponseDataAttributesValues) SetName(v string) {
    o.Name = &v
}

func (o Product202309GetAttributesResponseDataAttributesValues) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309GetAttributesResponseDataAttributesValues) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.IconUrl) {
        toSerialize["icon_url"] = o.IconUrl
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Name) {
        toSerialize["name"] = o.Name
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202309GetAttributesResponseDataAttributesValues) UnmarshalJSON(data []byte) (err error) {
    varProduct202309GetAttributesResponseDataAttributesValues := _Product202309GetAttributesResponseDataAttributesValues{}

    err = json.Unmarshal(data, &varProduct202309GetAttributesResponseDataAttributesValues)

    if err != nil {
        return err
    }

    *o = Product202309GetAttributesResponseDataAttributesValues(varProduct202309GetAttributesResponseDataAttributesValues)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "icon_url")
        delete(additionalProperties, "id")
        delete(additionalProperties, "name")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202309GetAttributesResponseDataAttributesValues struct {
	value *Product202309GetAttributesResponseDataAttributesValues
	isSet bool
}

func (v NullableProduct202309GetAttributesResponseDataAttributesValues) Get() *Product202309GetAttributesResponseDataAttributesValues {
	return v.value
}

func (v *NullableProduct202309GetAttributesResponseDataAttributesValues) Set(val *Product202309GetAttributesResponseDataAttributesValues) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309GetAttributesResponseDataAttributesValues) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309GetAttributesResponseDataAttributesValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309GetAttributesResponseDataAttributesValues(val *Product202309GetAttributesResponseDataAttributesValues) *NullableProduct202309GetAttributesResponseDataAttributesValues {
	return &NullableProduct202309GetAttributesResponseDataAttributesValues{value: val, isSet: true}
}

func (v NullableProduct202309GetAttributesResponseDataAttributesValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309GetAttributesResponseDataAttributesValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


