/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309GetProductResponseDataSkusCombinedSkusCategories type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309GetProductResponseDataSkusCombinedSkusCategories{}

// Product202309GetProductResponseDataSkusCombinedSkusCategories struct for Product202309GetProductResponseDataSkusCombinedSkusCategories
type Product202309GetProductResponseDataSkusCombinedSkusCategories struct {
    // The ID of the category of the source product included in the virtual bundle.
    Id *string `json:"id,omitempty"`
    // A flag to indicate if the category is a leaf category. 
    IsLeaf *bool `json:"is_leaf,omitempty"`
    // The name of the category in the country where the shop operates.
    LocalName *string `json:"local_name,omitempty"`
    // The parent category ID of the source product included in the virtual bundle.
    ParentId *string `json:"parent_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202309GetProductResponseDataSkusCombinedSkusCategories Product202309GetProductResponseDataSkusCombinedSkusCategories

// NewProduct202309GetProductResponseDataSkusCombinedSkusCategories instantiates a new Product202309GetProductResponseDataSkusCombinedSkusCategories object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309GetProductResponseDataSkusCombinedSkusCategories() *Product202309GetProductResponseDataSkusCombinedSkusCategories {
    this := Product202309GetProductResponseDataSkusCombinedSkusCategories{}
    return &this
}

// NewProduct202309GetProductResponseDataSkusCombinedSkusCategoriesWithDefaults instantiates a new Product202309GetProductResponseDataSkusCombinedSkusCategories object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309GetProductResponseDataSkusCombinedSkusCategoriesWithDefaults() *Product202309GetProductResponseDataSkusCombinedSkusCategories {
    this := Product202309GetProductResponseDataSkusCombinedSkusCategories{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) SetId(v string) {
    o.Id = &v
}

// GetIsLeaf returns the IsLeaf field value if set, zero value otherwise.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetIsLeaf() bool {
    if o == nil || utils.IsNil(o.IsLeaf) {
        var ret bool
        return ret
    }
    return *o.IsLeaf
}

// GetIsLeafOk returns a tuple with the IsLeaf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetIsLeafOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.IsLeaf) {
        return nil, false
    }
    return o.IsLeaf, true
}

// HasIsLeaf returns a boolean if a field has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) HasIsLeaf() bool {
    if o != nil && !utils.IsNil(o.IsLeaf) {
        return true
    }

    return false
}

// SetIsLeaf gets a reference to the given bool and assigns it to the IsLeaf field.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) SetIsLeaf(v bool) {
    o.IsLeaf = &v
}

// GetLocalName returns the LocalName field value if set, zero value otherwise.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetLocalName() string {
    if o == nil || utils.IsNil(o.LocalName) {
        var ret string
        return ret
    }
    return *o.LocalName
}

// GetLocalNameOk returns a tuple with the LocalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetLocalNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.LocalName) {
        return nil, false
    }
    return o.LocalName, true
}

// HasLocalName returns a boolean if a field has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) HasLocalName() bool {
    if o != nil && !utils.IsNil(o.LocalName) {
        return true
    }

    return false
}

// SetLocalName gets a reference to the given string and assigns it to the LocalName field.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) SetLocalName(v string) {
    o.LocalName = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetParentId() string {
    if o == nil || utils.IsNil(o.ParentId) {
        var ret string
        return ret
    }
    return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) GetParentIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ParentId) {
        return nil, false
    }
    return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) HasParentId() bool {
    if o != nil && !utils.IsNil(o.ParentId) {
        return true
    }

    return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) SetParentId(v string) {
    o.ParentId = &v
}

func (o Product202309GetProductResponseDataSkusCombinedSkusCategories) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309GetProductResponseDataSkusCombinedSkusCategories) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.IsLeaf) {
        toSerialize["is_leaf"] = o.IsLeaf
    }
    if !utils.IsNil(o.LocalName) {
        toSerialize["local_name"] = o.LocalName
    }
    if !utils.IsNil(o.ParentId) {
        toSerialize["parent_id"] = o.ParentId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202309GetProductResponseDataSkusCombinedSkusCategories) UnmarshalJSON(data []byte) (err error) {
    varProduct202309GetProductResponseDataSkusCombinedSkusCategories := _Product202309GetProductResponseDataSkusCombinedSkusCategories{}

    err = json.Unmarshal(data, &varProduct202309GetProductResponseDataSkusCombinedSkusCategories)

    if err != nil {
        return err
    }

    *o = Product202309GetProductResponseDataSkusCombinedSkusCategories(varProduct202309GetProductResponseDataSkusCombinedSkusCategories)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "id")
        delete(additionalProperties, "is_leaf")
        delete(additionalProperties, "local_name")
        delete(additionalProperties, "parent_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories struct {
	value *Product202309GetProductResponseDataSkusCombinedSkusCategories
	isSet bool
}

func (v NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories) Get() *Product202309GetProductResponseDataSkusCombinedSkusCategories {
	return v.value
}

func (v *NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories) Set(val *Product202309GetProductResponseDataSkusCombinedSkusCategories) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309GetProductResponseDataSkusCombinedSkusCategories(val *Product202309GetProductResponseDataSkusCombinedSkusCategories) *NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories {
	return &NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories{value: val, isSet: true}
}

func (v NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309GetProductResponseDataSkusCombinedSkusCategories) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


