/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309PartialEditProductRequestBodyReplicatedProductsSkus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309PartialEditProductRequestBodyReplicatedProductsSkus{}

// Product202309PartialEditProductRequestBodyReplicatedProductsSkus struct for Product202309PartialEditProductRequestBodyReplicatedProductsSkus
type Product202309PartialEditProductRequestBodyReplicatedProductsSkus struct {
    // An external identifier used in an external ecommerce platform. This is used to associate the SKU between TikTok Shop and the external ecommerce platform.  Max length: 999 characters
    ExternalSkuId *string `json:"external_sku_id,omitempty"`
    // The SKU ID generated by TikTok Shop. Provide this for existing SKUs
    Id *string `json:"id,omitempty"`
    // SKU inventory information per warehouse.
    Inventory []Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory `json:"inventory,omitempty"`
    Price *Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice `json:"price,omitempty"`
    // The seller_sku value of the source product above. - Valid length: 1-50 characters - Format: Text without spaces
    SellerSku *string `json:"seller_sku,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202309PartialEditProductRequestBodyReplicatedProductsSkus Product202309PartialEditProductRequestBodyReplicatedProductsSkus

// NewProduct202309PartialEditProductRequestBodyReplicatedProductsSkus instantiates a new Product202309PartialEditProductRequestBodyReplicatedProductsSkus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309PartialEditProductRequestBodyReplicatedProductsSkus() *Product202309PartialEditProductRequestBodyReplicatedProductsSkus {
    this := Product202309PartialEditProductRequestBodyReplicatedProductsSkus{}
    return &this
}

// NewProduct202309PartialEditProductRequestBodyReplicatedProductsSkusWithDefaults instantiates a new Product202309PartialEditProductRequestBodyReplicatedProductsSkus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309PartialEditProductRequestBodyReplicatedProductsSkusWithDefaults() *Product202309PartialEditProductRequestBodyReplicatedProductsSkus {
    this := Product202309PartialEditProductRequestBodyReplicatedProductsSkus{}
    return &this
}

// GetExternalSkuId returns the ExternalSkuId field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetExternalSkuId() string {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        var ret string
        return ret
    }
    return *o.ExternalSkuId
}

// GetExternalSkuIdOk returns a tuple with the ExternalSkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetExternalSkuIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        return nil, false
    }
    return o.ExternalSkuId, true
}

// HasExternalSkuId returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) HasExternalSkuId() bool {
    if o != nil && !utils.IsNil(o.ExternalSkuId) {
        return true
    }

    return false
}

// SetExternalSkuId gets a reference to the given string and assigns it to the ExternalSkuId field.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) SetExternalSkuId(v string) {
    o.ExternalSkuId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) SetId(v string) {
    o.Id = &v
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetInventory() []Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory {
    if o == nil || utils.IsNil(o.Inventory) {
        var ret []Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory
        return ret
    }
    return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetInventoryOk() ([]Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory, bool) {
    if o == nil || utils.IsNil(o.Inventory) {
        return nil, false
    }
    return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) HasInventory() bool {
    if o != nil && !utils.IsNil(o.Inventory) {
        return true
    }

    return false
}

// SetInventory gets a reference to the given []Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory and assigns it to the Inventory field.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) SetInventory(v []Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory) {
    o.Inventory = v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetPrice() Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice {
    if o == nil || utils.IsNil(o.Price) {
        var ret Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice
        return ret
    }
    return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetPriceOk() (*Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice, bool) {
    if o == nil || utils.IsNil(o.Price) {
        return nil, false
    }
    return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) HasPrice() bool {
    if o != nil && !utils.IsNil(o.Price) {
        return true
    }

    return false
}

// SetPrice gets a reference to the given Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice and assigns it to the Price field.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) SetPrice(v Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice) {
    o.Price = &v
}

// GetSellerSku returns the SellerSku field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetSellerSku() string {
    if o == nil || utils.IsNil(o.SellerSku) {
        var ret string
        return ret
    }
    return *o.SellerSku
}

// GetSellerSkuOk returns a tuple with the SellerSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) GetSellerSkuOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerSku) {
        return nil, false
    }
    return o.SellerSku, true
}

// HasSellerSku returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) HasSellerSku() bool {
    if o != nil && !utils.IsNil(o.SellerSku) {
        return true
    }

    return false
}

// SetSellerSku gets a reference to the given string and assigns it to the SellerSku field.
func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) SetSellerSku(v string) {
    o.SellerSku = &v
}

func (o Product202309PartialEditProductRequestBodyReplicatedProductsSkus) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309PartialEditProductRequestBodyReplicatedProductsSkus) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ExternalSkuId) {
        toSerialize["external_sku_id"] = o.ExternalSkuId
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Inventory) {
        toSerialize["inventory"] = o.Inventory
    }
    if !utils.IsNil(o.Price) {
        toSerialize["price"] = o.Price
    }
    if !utils.IsNil(o.SellerSku) {
        toSerialize["seller_sku"] = o.SellerSku
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) UnmarshalJSON(data []byte) (err error) {
    varProduct202309PartialEditProductRequestBodyReplicatedProductsSkus := _Product202309PartialEditProductRequestBodyReplicatedProductsSkus{}

    err = json.Unmarshal(data, &varProduct202309PartialEditProductRequestBodyReplicatedProductsSkus)

    if err != nil {
        return err
    }

    *o = Product202309PartialEditProductRequestBodyReplicatedProductsSkus(varProduct202309PartialEditProductRequestBodyReplicatedProductsSkus)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "external_sku_id")
        delete(additionalProperties, "id")
        delete(additionalProperties, "inventory")
        delete(additionalProperties, "price")
        delete(additionalProperties, "seller_sku")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus struct {
	value *Product202309PartialEditProductRequestBodyReplicatedProductsSkus
	isSet bool
}

func (v NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus) Get() *Product202309PartialEditProductRequestBodyReplicatedProductsSkus {
	return v.value
}

func (v *NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus) Set(val *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus(val *Product202309PartialEditProductRequestBodyReplicatedProductsSkus) *NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus {
	return &NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus{value: val, isSet: true}
}

func (v NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309PartialEditProductRequestBodyReplicatedProductsSkus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


