/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer_service_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the CustomerService202309GetConversationMessagesResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CustomerService202309GetConversationMessagesResponseData{}

// CustomerService202309GetConversationMessagesResponseData struct for CustomerService202309GetConversationMessagesResponseData
type CustomerService202309GetConversationMessagesResponseData struct {
    // Messages in conversation.
    Messages []CustomerService202309GetConversationMessagesResponseDataMessages `json:"messages,omitempty"`
    // The index indicates where we should start on the next page.  If there is no more record, this field will be \"\"(empty string). Put this value to request param \"page_token\" for the next page query.
    NextPageToken *string `json:"next_page_token,omitempty"`
    // If your app encounters a message type it doesn't support, you can display the text to guide the user to check the message in TikTok Shop. The content of the message depends on the specific `locale`.
    UnsupportedMsgTips *string `json:"unsupported_msg_tips,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _CustomerService202309GetConversationMessagesResponseData CustomerService202309GetConversationMessagesResponseData

// NewCustomerService202309GetConversationMessagesResponseData instantiates a new CustomerService202309GetConversationMessagesResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerService202309GetConversationMessagesResponseData() *CustomerService202309GetConversationMessagesResponseData {
    this := CustomerService202309GetConversationMessagesResponseData{}
    return &this
}

// NewCustomerService202309GetConversationMessagesResponseDataWithDefaults instantiates a new CustomerService202309GetConversationMessagesResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerService202309GetConversationMessagesResponseDataWithDefaults() *CustomerService202309GetConversationMessagesResponseData {
    this := CustomerService202309GetConversationMessagesResponseData{}
    return &this
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *CustomerService202309GetConversationMessagesResponseData) GetMessages() []CustomerService202309GetConversationMessagesResponseDataMessages {
    if o == nil || utils.IsNil(o.Messages) {
        var ret []CustomerService202309GetConversationMessagesResponseDataMessages
        return ret
    }
    return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309GetConversationMessagesResponseData) GetMessagesOk() ([]CustomerService202309GetConversationMessagesResponseDataMessages, bool) {
    if o == nil || utils.IsNil(o.Messages) {
        return nil, false
    }
    return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *CustomerService202309GetConversationMessagesResponseData) HasMessages() bool {
    if o != nil && !utils.IsNil(o.Messages) {
        return true
    }

    return false
}

// SetMessages gets a reference to the given []CustomerService202309GetConversationMessagesResponseDataMessages and assigns it to the Messages field.
func (o *CustomerService202309GetConversationMessagesResponseData) SetMessages(v []CustomerService202309GetConversationMessagesResponseDataMessages) {
    o.Messages = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *CustomerService202309GetConversationMessagesResponseData) GetNextPageToken() string {
    if o == nil || utils.IsNil(o.NextPageToken) {
        var ret string
        return ret
    }
    return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309GetConversationMessagesResponseData) GetNextPageTokenOk() (*string, bool) {
    if o == nil || utils.IsNil(o.NextPageToken) {
        return nil, false
    }
    return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *CustomerService202309GetConversationMessagesResponseData) HasNextPageToken() bool {
    if o != nil && !utils.IsNil(o.NextPageToken) {
        return true
    }

    return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *CustomerService202309GetConversationMessagesResponseData) SetNextPageToken(v string) {
    o.NextPageToken = &v
}

// GetUnsupportedMsgTips returns the UnsupportedMsgTips field value if set, zero value otherwise.
func (o *CustomerService202309GetConversationMessagesResponseData) GetUnsupportedMsgTips() string {
    if o == nil || utils.IsNil(o.UnsupportedMsgTips) {
        var ret string
        return ret
    }
    return *o.UnsupportedMsgTips
}

// GetUnsupportedMsgTipsOk returns a tuple with the UnsupportedMsgTips field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309GetConversationMessagesResponseData) GetUnsupportedMsgTipsOk() (*string, bool) {
    if o == nil || utils.IsNil(o.UnsupportedMsgTips) {
        return nil, false
    }
    return o.UnsupportedMsgTips, true
}

// HasUnsupportedMsgTips returns a boolean if a field has been set.
func (o *CustomerService202309GetConversationMessagesResponseData) HasUnsupportedMsgTips() bool {
    if o != nil && !utils.IsNil(o.UnsupportedMsgTips) {
        return true
    }

    return false
}

// SetUnsupportedMsgTips gets a reference to the given string and assigns it to the UnsupportedMsgTips field.
func (o *CustomerService202309GetConversationMessagesResponseData) SetUnsupportedMsgTips(v string) {
    o.UnsupportedMsgTips = &v
}

func (o CustomerService202309GetConversationMessagesResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o CustomerService202309GetConversationMessagesResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Messages) {
        toSerialize["messages"] = o.Messages
    }
    if !utils.IsNil(o.NextPageToken) {
        toSerialize["next_page_token"] = o.NextPageToken
    }
    if !utils.IsNil(o.UnsupportedMsgTips) {
        toSerialize["unsupported_msg_tips"] = o.UnsupportedMsgTips
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *CustomerService202309GetConversationMessagesResponseData) UnmarshalJSON(data []byte) (err error) {
    varCustomerService202309GetConversationMessagesResponseData := _CustomerService202309GetConversationMessagesResponseData{}

    err = json.Unmarshal(data, &varCustomerService202309GetConversationMessagesResponseData)

    if err != nil {
        return err
    }

    *o = CustomerService202309GetConversationMessagesResponseData(varCustomerService202309GetConversationMessagesResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "messages")
        delete(additionalProperties, "next_page_token")
        delete(additionalProperties, "unsupported_msg_tips")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableCustomerService202309GetConversationMessagesResponseData struct {
	value *CustomerService202309GetConversationMessagesResponseData
	isSet bool
}

func (v NullableCustomerService202309GetConversationMessagesResponseData) Get() *CustomerService202309GetConversationMessagesResponseData {
	return v.value
}

func (v *NullableCustomerService202309GetConversationMessagesResponseData) Set(val *CustomerService202309GetConversationMessagesResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerService202309GetConversationMessagesResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerService202309GetConversationMessagesResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerService202309GetConversationMessagesResponseData(val *CustomerService202309GetConversationMessagesResponseData) *NullableCustomerService202309GetConversationMessagesResponseData {
	return &NullableCustomerService202309GetConversationMessagesResponseData{value: val, isSet: true}
}

func (v NullableCustomerService202309GetConversationMessagesResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerService202309GetConversationMessagesResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


