/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer_service_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the CustomerService202309GetConversationsResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CustomerService202309GetConversationsResponse{}

// CustomerService202309GetConversationsResponse struct for CustomerService202309GetConversationsResponse
type CustomerService202309GetConversationsResponse struct {
    // The success or failure status code returned in API response.
    Code *int32 `json:"code,omitempty"`
    Data *CustomerService202309GetConversationsResponseData `json:"data,omitempty"`
    // The success or failure messages returned in API response. Reasons of failure will be described in the message.
    Message *string `json:"message,omitempty"`
    // Request log.
    RequestId *string `json:"request_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _CustomerService202309GetConversationsResponse CustomerService202309GetConversationsResponse

// NewCustomerService202309GetConversationsResponse instantiates a new CustomerService202309GetConversationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerService202309GetConversationsResponse() *CustomerService202309GetConversationsResponse {
    this := CustomerService202309GetConversationsResponse{}
    return &this
}

// NewCustomerService202309GetConversationsResponseWithDefaults instantiates a new CustomerService202309GetConversationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerService202309GetConversationsResponseWithDefaults() *CustomerService202309GetConversationsResponse {
    this := CustomerService202309GetConversationsResponse{}
    return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CustomerService202309GetConversationsResponse) GetCode() int32 {
    if o == nil || utils.IsNil(o.Code) {
        var ret int32
        return ret
    }
    return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309GetConversationsResponse) GetCodeOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Code) {
        return nil, false
    }
    return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CustomerService202309GetConversationsResponse) HasCode() bool {
    if o != nil && !utils.IsNil(o.Code) {
        return true
    }

    return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *CustomerService202309GetConversationsResponse) SetCode(v int32) {
    o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustomerService202309GetConversationsResponse) GetData() CustomerService202309GetConversationsResponseData {
    if o == nil || utils.IsNil(o.Data) {
        var ret CustomerService202309GetConversationsResponseData
        return ret
    }
    return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309GetConversationsResponse) GetDataOk() (*CustomerService202309GetConversationsResponseData, bool) {
    if o == nil || utils.IsNil(o.Data) {
        return nil, false
    }
    return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustomerService202309GetConversationsResponse) HasData() bool {
    if o != nil && !utils.IsNil(o.Data) {
        return true
    }

    return false
}

// SetData gets a reference to the given CustomerService202309GetConversationsResponseData and assigns it to the Data field.
func (o *CustomerService202309GetConversationsResponse) SetData(v CustomerService202309GetConversationsResponseData) {
    o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CustomerService202309GetConversationsResponse) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309GetConversationsResponse) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CustomerService202309GetConversationsResponse) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CustomerService202309GetConversationsResponse) SetMessage(v string) {
    o.Message = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CustomerService202309GetConversationsResponse) GetRequestId() string {
    if o == nil || utils.IsNil(o.RequestId) {
        var ret string
        return ret
    }
    return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309GetConversationsResponse) GetRequestIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RequestId) {
        return nil, false
    }
    return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CustomerService202309GetConversationsResponse) HasRequestId() bool {
    if o != nil && !utils.IsNil(o.RequestId) {
        return true
    }

    return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CustomerService202309GetConversationsResponse) SetRequestId(v string) {
    o.RequestId = &v
}

func (o CustomerService202309GetConversationsResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o CustomerService202309GetConversationsResponse) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Code) {
        toSerialize["code"] = o.Code
    }
    if !utils.IsNil(o.Data) {
        toSerialize["data"] = o.Data
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    if !utils.IsNil(o.RequestId) {
        toSerialize["request_id"] = o.RequestId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *CustomerService202309GetConversationsResponse) UnmarshalJSON(data []byte) (err error) {
    varCustomerService202309GetConversationsResponse := _CustomerService202309GetConversationsResponse{}

    err = json.Unmarshal(data, &varCustomerService202309GetConversationsResponse)

    if err != nil {
        return err
    }

    *o = CustomerService202309GetConversationsResponse(varCustomerService202309GetConversationsResponse)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "code")
        delete(additionalProperties, "data")
        delete(additionalProperties, "message")
        delete(additionalProperties, "request_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableCustomerService202309GetConversationsResponse struct {
	value *CustomerService202309GetConversationsResponse
	isSet bool
}

func (v NullableCustomerService202309GetConversationsResponse) Get() *CustomerService202309GetConversationsResponse {
	return v.value
}

func (v *NullableCustomerService202309GetConversationsResponse) Set(val *CustomerService202309GetConversationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerService202309GetConversationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerService202309GetConversationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerService202309GetConversationsResponse(val *CustomerService202309GetConversationsResponse) *NullableCustomerService202309GetConversationsResponse {
	return &NullableCustomerService202309GetConversationsResponse{value: val, isSet: true}
}

func (v NullableCustomerService202309GetConversationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerService202309GetConversationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


