/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer_service_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the CustomerService202309ReadMessageResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CustomerService202309ReadMessageResponse{}

// CustomerService202309ReadMessageResponse struct for CustomerService202309ReadMessageResponse
type CustomerService202309ReadMessageResponse struct {
    // The success or failure status code returned in API response.
    Code *int32 `json:"code,omitempty"`
    Data map[string]interface{} `json:"data,omitempty"`
    // The success or failure messages returned in API response. Reasons of failure will be described in the message.
    Message *string `json:"message,omitempty"`
    // Request log.
    RequestId *string `json:"request_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _CustomerService202309ReadMessageResponse CustomerService202309ReadMessageResponse

// NewCustomerService202309ReadMessageResponse instantiates a new CustomerService202309ReadMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerService202309ReadMessageResponse() *CustomerService202309ReadMessageResponse {
    this := CustomerService202309ReadMessageResponse{}
    return &this
}

// NewCustomerService202309ReadMessageResponseWithDefaults instantiates a new CustomerService202309ReadMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerService202309ReadMessageResponseWithDefaults() *CustomerService202309ReadMessageResponse {
    this := CustomerService202309ReadMessageResponse{}
    return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CustomerService202309ReadMessageResponse) GetCode() int32 {
    if o == nil || utils.IsNil(o.Code) {
        var ret int32
        return ret
    }
    return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309ReadMessageResponse) GetCodeOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Code) {
        return nil, false
    }
    return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CustomerService202309ReadMessageResponse) HasCode() bool {
    if o != nil && !utils.IsNil(o.Code) {
        return true
    }

    return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *CustomerService202309ReadMessageResponse) SetCode(v int32) {
    o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustomerService202309ReadMessageResponse) GetData() map[string]interface{} {
    if o == nil || utils.IsNil(o.Data) {
        var ret map[string]interface{}
        return ret
    }
    return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309ReadMessageResponse) GetDataOk() (map[string]interface{}, bool) {
    if o == nil || utils.IsNil(o.Data) {
        return map[string]interface{}{}, false
    }
    return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustomerService202309ReadMessageResponse) HasData() bool {
    if o != nil && !utils.IsNil(o.Data) {
        return true
    }

    return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *CustomerService202309ReadMessageResponse) SetData(v map[string]interface{}) {
    o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CustomerService202309ReadMessageResponse) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309ReadMessageResponse) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CustomerService202309ReadMessageResponse) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CustomerService202309ReadMessageResponse) SetMessage(v string) {
    o.Message = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CustomerService202309ReadMessageResponse) GetRequestId() string {
    if o == nil || utils.IsNil(o.RequestId) {
        var ret string
        return ret
    }
    return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309ReadMessageResponse) GetRequestIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RequestId) {
        return nil, false
    }
    return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CustomerService202309ReadMessageResponse) HasRequestId() bool {
    if o != nil && !utils.IsNil(o.RequestId) {
        return true
    }

    return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CustomerService202309ReadMessageResponse) SetRequestId(v string) {
    o.RequestId = &v
}

func (o CustomerService202309ReadMessageResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o CustomerService202309ReadMessageResponse) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Code) {
        toSerialize["code"] = o.Code
    }
    if !utils.IsNil(o.Data) {
        toSerialize["data"] = o.Data
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    if !utils.IsNil(o.RequestId) {
        toSerialize["request_id"] = o.RequestId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *CustomerService202309ReadMessageResponse) UnmarshalJSON(data []byte) (err error) {
    varCustomerService202309ReadMessageResponse := _CustomerService202309ReadMessageResponse{}

    err = json.Unmarshal(data, &varCustomerService202309ReadMessageResponse)

    if err != nil {
        return err
    }

    *o = CustomerService202309ReadMessageResponse(varCustomerService202309ReadMessageResponse)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "code")
        delete(additionalProperties, "data")
        delete(additionalProperties, "message")
        delete(additionalProperties, "request_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableCustomerService202309ReadMessageResponse struct {
	value *CustomerService202309ReadMessageResponse
	isSet bool
}

func (v NullableCustomerService202309ReadMessageResponse) Get() *CustomerService202309ReadMessageResponse {
	return v.value
}

func (v *NullableCustomerService202309ReadMessageResponse) Set(val *CustomerService202309ReadMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerService202309ReadMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerService202309ReadMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerService202309ReadMessageResponse(val *CustomerService202309ReadMessageResponse) *NullableCustomerService202309ReadMessageResponse {
	return &NullableCustomerService202309ReadMessageResponse{value: val, isSet: true}
}

func (v NullableCustomerService202309ReadMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerService202309ReadMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


