/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customer_service_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the CustomerService202309SendMessageRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CustomerService202309SendMessageRequestBody{}

// CustomerService202309SendMessageRequestBody struct for CustomerService202309SendMessageRequestBody
type CustomerService202309SendMessageRequestBody struct {
    // Message content, in JSON serialized string.  Examples of content for each type of message are listed below: ​ - TEXT: {     \"content\": \"hi, I want to get refunded.\" } (Note: Max 2000 characters. Do not use sensitive words that violate TikTok Shop terms & policies.) ​ - PRODUCT_CARD {     \"product_id\": \"7494560109732334265\" } ​ - ORDER_CARD: {     \"order_id\": \"7494560109732334267\" }  - RETURN_REFUND_CARD: {     \"order_id\": \"7494560109732334267\",     \"sku_id\": \"7494560109732363423\" } Note: The order of the RETURN_REFUND_CARD to send must meet after-sale conditions. To check the eligibility, use [Get Aftersale Eligibility](650ab645c16ffe02b8f2e1c1). ​ - IMAGE: {     \"url\":\"https://p16-oec-va.ibyteimg.com/tos-maliva-i-o3syd03w52-us/2ca53c34ad8443e6b39f4e0153d3aed4~tplv-o3syd03w52-origin-image.image?from=1320446476\",     \"width\": 1280,     \"height\": 720 }  Note: You can get the value of `url` by calling [Upload Buyer Messages Image](650a599d0fcef602bf2a1dc8).  - COUPON_CARD: {     \"coupon_id\": \"7262992004278206762\" } Note: Coupons that can be sent in  a message must meet all the following conditions: 1. `display_type==CHAT` or `display_type==REGULAR` 2. `status==ONGOING` 3. `creation_source==SELLER_CENTER` 4. `target_buyer_segment!=REPEAT_CUSTOMERS`
    Content *string `json:"content,omitempty"`
    // Message type. Possible enumerations: - `TEXT` - `IMAGE` - `PRODUCT_CARD` - `ORDER_CARD` - `RETURN_REFUND_CARD` - `COUPON_CARD`
    Type *string `json:"type,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _CustomerService202309SendMessageRequestBody CustomerService202309SendMessageRequestBody

// NewCustomerService202309SendMessageRequestBody instantiates a new CustomerService202309SendMessageRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerService202309SendMessageRequestBody() *CustomerService202309SendMessageRequestBody {
    this := CustomerService202309SendMessageRequestBody{}
    return &this
}

// NewCustomerService202309SendMessageRequestBodyWithDefaults instantiates a new CustomerService202309SendMessageRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerService202309SendMessageRequestBodyWithDefaults() *CustomerService202309SendMessageRequestBody {
    this := CustomerService202309SendMessageRequestBody{}
    return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *CustomerService202309SendMessageRequestBody) GetContent() string {
    if o == nil || utils.IsNil(o.Content) {
        var ret string
        return ret
    }
    return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309SendMessageRequestBody) GetContentOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Content) {
        return nil, false
    }
    return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *CustomerService202309SendMessageRequestBody) HasContent() bool {
    if o != nil && !utils.IsNil(o.Content) {
        return true
    }

    return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *CustomerService202309SendMessageRequestBody) SetContent(v string) {
    o.Content = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CustomerService202309SendMessageRequestBody) GetType() string {
    if o == nil || utils.IsNil(o.Type) {
        var ret string
        return ret
    }
    return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerService202309SendMessageRequestBody) GetTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Type) {
        return nil, false
    }
    return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CustomerService202309SendMessageRequestBody) HasType() bool {
    if o != nil && !utils.IsNil(o.Type) {
        return true
    }

    return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CustomerService202309SendMessageRequestBody) SetType(v string) {
    o.Type = &v
}

func (o CustomerService202309SendMessageRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o CustomerService202309SendMessageRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Content) {
        toSerialize["content"] = o.Content
    }
    if !utils.IsNil(o.Type) {
        toSerialize["type"] = o.Type
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *CustomerService202309SendMessageRequestBody) UnmarshalJSON(data []byte) (err error) {
    varCustomerService202309SendMessageRequestBody := _CustomerService202309SendMessageRequestBody{}

    err = json.Unmarshal(data, &varCustomerService202309SendMessageRequestBody)

    if err != nil {
        return err
    }

    *o = CustomerService202309SendMessageRequestBody(varCustomerService202309SendMessageRequestBody)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "content")
        delete(additionalProperties, "type")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableCustomerService202309SendMessageRequestBody struct {
	value *CustomerService202309SendMessageRequestBody
	isSet bool
}

func (v NullableCustomerService202309SendMessageRequestBody) Get() *CustomerService202309SendMessageRequestBody {
	return v.value
}

func (v *NullableCustomerService202309SendMessageRequestBody) Set(val *CustomerService202309SendMessageRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerService202309SendMessageRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerService202309SendMessageRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerService202309SendMessageRequestBody(val *CustomerService202309SendMessageRequestBody) *NullableCustomerService202309SendMessageRequestBody {
	return &NullableCustomerService202309SendMessageRequestBody{value: val, isSet: true}
}

func (v NullableCustomerService202309SendMessageRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerService202309SendMessageRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


