/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509EditProductRequestBodyReplicatedProductsSkusPrice type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509EditProductRequestBodyReplicatedProductsSkusPrice{}

// Product202509EditProductRequestBodyReplicatedProductsSkusPrice struct for Product202509EditProductRequestBodyReplicatedProductsSkusPrice
type Product202509EditProductRequestBodyReplicatedProductsSkusPrice struct {
    // The currency. You must specify the local currency in the target market. Possible values: - EUR: France, Germany, Ireland, Italy, Spain - GBP: United Kingdom - IDR: Indonesia - JPY: Japanese - MYR: Malaysia - PHP: Philippines - SGD: Singapore - THB: Thailand - USD: United States - VND: Vietnam
    Currency *string `json:"currency,omitempty"`
    // The SKU's local display price shown on the product page before any discounts.  Refer to [Product Pricing](https://partner.tiktokshop.com/docv2/page/67e1288d76cfee049d9af858) for the allowed price ranges in each market.
    SalePrice *string `json:"sale_price,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509EditProductRequestBodyReplicatedProductsSkusPrice Product202509EditProductRequestBodyReplicatedProductsSkusPrice

// NewProduct202509EditProductRequestBodyReplicatedProductsSkusPrice instantiates a new Product202509EditProductRequestBodyReplicatedProductsSkusPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509EditProductRequestBodyReplicatedProductsSkusPrice() *Product202509EditProductRequestBodyReplicatedProductsSkusPrice {
    this := Product202509EditProductRequestBodyReplicatedProductsSkusPrice{}
    return &this
}

// NewProduct202509EditProductRequestBodyReplicatedProductsSkusPriceWithDefaults instantiates a new Product202509EditProductRequestBodyReplicatedProductsSkusPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509EditProductRequestBodyReplicatedProductsSkusPriceWithDefaults() *Product202509EditProductRequestBodyReplicatedProductsSkusPrice {
    this := Product202509EditProductRequestBodyReplicatedProductsSkusPrice{}
    return &this
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) SetCurrency(v string) {
    o.Currency = &v
}

// GetSalePrice returns the SalePrice field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) GetSalePrice() string {
    if o == nil || utils.IsNil(o.SalePrice) {
        var ret string
        return ret
    }
    return *o.SalePrice
}

// GetSalePriceOk returns a tuple with the SalePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) GetSalePriceOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SalePrice) {
        return nil, false
    }
    return o.SalePrice, true
}

// HasSalePrice returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) HasSalePrice() bool {
    if o != nil && !utils.IsNil(o.SalePrice) {
        return true
    }

    return false
}

// SetSalePrice gets a reference to the given string and assigns it to the SalePrice field.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) SetSalePrice(v string) {
    o.SalePrice = &v
}

func (o Product202509EditProductRequestBodyReplicatedProductsSkusPrice) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509EditProductRequestBodyReplicatedProductsSkusPrice) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }
    if !utils.IsNil(o.SalePrice) {
        toSerialize["sale_price"] = o.SalePrice
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) UnmarshalJSON(data []byte) (err error) {
    varProduct202509EditProductRequestBodyReplicatedProductsSkusPrice := _Product202509EditProductRequestBodyReplicatedProductsSkusPrice{}

    err = json.Unmarshal(data, &varProduct202509EditProductRequestBodyReplicatedProductsSkusPrice)

    if err != nil {
        return err
    }

    *o = Product202509EditProductRequestBodyReplicatedProductsSkusPrice(varProduct202509EditProductRequestBodyReplicatedProductsSkusPrice)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "currency")
        delete(additionalProperties, "sale_price")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice struct {
	value *Product202509EditProductRequestBodyReplicatedProductsSkusPrice
	isSet bool
}

func (v NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice) Get() *Product202509EditProductRequestBodyReplicatedProductsSkusPrice {
	return v.value
}

func (v *NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice) Set(val *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice(val *Product202509EditProductRequestBodyReplicatedProductsSkusPrice) *NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice {
	return &NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice{value: val, isSet: true}
}

func (v NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509EditProductRequestBodyReplicatedProductsSkusPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


