/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509EditProductRequestBodyReplicatedProductsSkus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509EditProductRequestBodyReplicatedProductsSkus{}

// Product202509EditProductRequestBodyReplicatedProductsSkus struct for Product202509EditProductRequestBodyReplicatedProductsSkus
type Product202509EditProductRequestBodyReplicatedProductsSkus struct {
    // The SKU ID generated by TikTok Shop. Provide this for existing SKUs.
    Id *string `json:"id,omitempty"`
    // SKU inventory information per warehouse.
    Inventory []Product202509EditProductRequestBodyReplicatedProductsSkusInventory `json:"inventory,omitempty"`
    Price *Product202509EditProductRequestBodyReplicatedProductsSkusPrice `json:"price,omitempty"`
    // The seller_sku value of the source product above. Provide this for new SKUs. - Valid length: 1-50 characters - Format: Text without spaces
    SellerSku *string `json:"seller_sku,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509EditProductRequestBodyReplicatedProductsSkus Product202509EditProductRequestBodyReplicatedProductsSkus

// NewProduct202509EditProductRequestBodyReplicatedProductsSkus instantiates a new Product202509EditProductRequestBodyReplicatedProductsSkus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509EditProductRequestBodyReplicatedProductsSkus() *Product202509EditProductRequestBodyReplicatedProductsSkus {
    this := Product202509EditProductRequestBodyReplicatedProductsSkus{}
    return &this
}

// NewProduct202509EditProductRequestBodyReplicatedProductsSkusWithDefaults instantiates a new Product202509EditProductRequestBodyReplicatedProductsSkus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509EditProductRequestBodyReplicatedProductsSkusWithDefaults() *Product202509EditProductRequestBodyReplicatedProductsSkus {
    this := Product202509EditProductRequestBodyReplicatedProductsSkus{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) SetId(v string) {
    o.Id = &v
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetInventory() []Product202509EditProductRequestBodyReplicatedProductsSkusInventory {
    if o == nil || utils.IsNil(o.Inventory) {
        var ret []Product202509EditProductRequestBodyReplicatedProductsSkusInventory
        return ret
    }
    return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetInventoryOk() ([]Product202509EditProductRequestBodyReplicatedProductsSkusInventory, bool) {
    if o == nil || utils.IsNil(o.Inventory) {
        return nil, false
    }
    return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) HasInventory() bool {
    if o != nil && !utils.IsNil(o.Inventory) {
        return true
    }

    return false
}

// SetInventory gets a reference to the given []Product202509EditProductRequestBodyReplicatedProductsSkusInventory and assigns it to the Inventory field.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) SetInventory(v []Product202509EditProductRequestBodyReplicatedProductsSkusInventory) {
    o.Inventory = v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetPrice() Product202509EditProductRequestBodyReplicatedProductsSkusPrice {
    if o == nil || utils.IsNil(o.Price) {
        var ret Product202509EditProductRequestBodyReplicatedProductsSkusPrice
        return ret
    }
    return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetPriceOk() (*Product202509EditProductRequestBodyReplicatedProductsSkusPrice, bool) {
    if o == nil || utils.IsNil(o.Price) {
        return nil, false
    }
    return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) HasPrice() bool {
    if o != nil && !utils.IsNil(o.Price) {
        return true
    }

    return false
}

// SetPrice gets a reference to the given Product202509EditProductRequestBodyReplicatedProductsSkusPrice and assigns it to the Price field.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) SetPrice(v Product202509EditProductRequestBodyReplicatedProductsSkusPrice) {
    o.Price = &v
}

// GetSellerSku returns the SellerSku field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetSellerSku() string {
    if o == nil || utils.IsNil(o.SellerSku) {
        var ret string
        return ret
    }
    return *o.SellerSku
}

// GetSellerSkuOk returns a tuple with the SellerSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) GetSellerSkuOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerSku) {
        return nil, false
    }
    return o.SellerSku, true
}

// HasSellerSku returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) HasSellerSku() bool {
    if o != nil && !utils.IsNil(o.SellerSku) {
        return true
    }

    return false
}

// SetSellerSku gets a reference to the given string and assigns it to the SellerSku field.
func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) SetSellerSku(v string) {
    o.SellerSku = &v
}

func (o Product202509EditProductRequestBodyReplicatedProductsSkus) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509EditProductRequestBodyReplicatedProductsSkus) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Inventory) {
        toSerialize["inventory"] = o.Inventory
    }
    if !utils.IsNil(o.Price) {
        toSerialize["price"] = o.Price
    }
    if !utils.IsNil(o.SellerSku) {
        toSerialize["seller_sku"] = o.SellerSku
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509EditProductRequestBodyReplicatedProductsSkus) UnmarshalJSON(data []byte) (err error) {
    varProduct202509EditProductRequestBodyReplicatedProductsSkus := _Product202509EditProductRequestBodyReplicatedProductsSkus{}

    err = json.Unmarshal(data, &varProduct202509EditProductRequestBodyReplicatedProductsSkus)

    if err != nil {
        return err
    }

    *o = Product202509EditProductRequestBodyReplicatedProductsSkus(varProduct202509EditProductRequestBodyReplicatedProductsSkus)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "id")
        delete(additionalProperties, "inventory")
        delete(additionalProperties, "price")
        delete(additionalProperties, "seller_sku")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509EditProductRequestBodyReplicatedProductsSkus struct {
	value *Product202509EditProductRequestBodyReplicatedProductsSkus
	isSet bool
}

func (v NullableProduct202509EditProductRequestBodyReplicatedProductsSkus) Get() *Product202509EditProductRequestBodyReplicatedProductsSkus {
	return v.value
}

func (v *NullableProduct202509EditProductRequestBodyReplicatedProductsSkus) Set(val *Product202509EditProductRequestBodyReplicatedProductsSkus) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509EditProductRequestBodyReplicatedProductsSkus) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509EditProductRequestBodyReplicatedProductsSkus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509EditProductRequestBodyReplicatedProductsSkus(val *Product202509EditProductRequestBodyReplicatedProductsSkus) *NullableProduct202509EditProductRequestBodyReplicatedProductsSkus {
	return &NullableProduct202509EditProductRequestBodyReplicatedProductsSkus{value: val, isSet: true}
}

func (v NullableProduct202509EditProductRequestBodyReplicatedProductsSkus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509EditProductRequestBodyReplicatedProductsSkus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


