/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509EditProductRequestBodySkusListPrice type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509EditProductRequestBodySkusListPrice{}

// Product202509EditProductRequestBodySkusListPrice struct for Product202509EditProductRequestBodySkusListPrice
type Product202509EditProductRequestBodySkusListPrice struct {
    // The price amount. Valid range: [0.01, 7600]   **Note**:  - The value must be equal to or greater than `skus.price.amount`. Otherwise, it will be discarded. - If the value is verified to be legitimate by the audit team, it will be stored and returned in the [Get Product API](6509d85b4a0bb702c057fdda).
    Amount *string `json:"amount,omitempty"`
    // The currency. Possible values: USD
    Currency *string `json:"currency,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509EditProductRequestBodySkusListPrice Product202509EditProductRequestBodySkusListPrice

// NewProduct202509EditProductRequestBodySkusListPrice instantiates a new Product202509EditProductRequestBodySkusListPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509EditProductRequestBodySkusListPrice() *Product202509EditProductRequestBodySkusListPrice {
    this := Product202509EditProductRequestBodySkusListPrice{}
    return &this
}

// NewProduct202509EditProductRequestBodySkusListPriceWithDefaults instantiates a new Product202509EditProductRequestBodySkusListPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509EditProductRequestBodySkusListPriceWithDefaults() *Product202509EditProductRequestBodySkusListPrice {
    this := Product202509EditProductRequestBodySkusListPrice{}
    return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodySkusListPrice) GetAmount() string {
    if o == nil || utils.IsNil(o.Amount) {
        var ret string
        return ret
    }
    return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodySkusListPrice) GetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Amount) {
        return nil, false
    }
    return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodySkusListPrice) HasAmount() bool {
    if o != nil && !utils.IsNil(o.Amount) {
        return true
    }

    return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *Product202509EditProductRequestBodySkusListPrice) SetAmount(v string) {
    o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Product202509EditProductRequestBodySkusListPrice) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509EditProductRequestBodySkusListPrice) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Product202509EditProductRequestBodySkusListPrice) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Product202509EditProductRequestBodySkusListPrice) SetCurrency(v string) {
    o.Currency = &v
}

func (o Product202509EditProductRequestBodySkusListPrice) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509EditProductRequestBodySkusListPrice) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Amount) {
        toSerialize["amount"] = o.Amount
    }
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509EditProductRequestBodySkusListPrice) UnmarshalJSON(data []byte) (err error) {
    varProduct202509EditProductRequestBodySkusListPrice := _Product202509EditProductRequestBodySkusListPrice{}

    err = json.Unmarshal(data, &varProduct202509EditProductRequestBodySkusListPrice)

    if err != nil {
        return err
    }

    *o = Product202509EditProductRequestBodySkusListPrice(varProduct202509EditProductRequestBodySkusListPrice)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "amount")
        delete(additionalProperties, "currency")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509EditProductRequestBodySkusListPrice struct {
	value *Product202509EditProductRequestBodySkusListPrice
	isSet bool
}

func (v NullableProduct202509EditProductRequestBodySkusListPrice) Get() *Product202509EditProductRequestBodySkusListPrice {
	return v.value
}

func (v *NullableProduct202509EditProductRequestBodySkusListPrice) Set(val *Product202509EditProductRequestBodySkusListPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509EditProductRequestBodySkusListPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509EditProductRequestBodySkusListPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509EditProductRequestBodySkusListPrice(val *Product202509EditProductRequestBodySkusListPrice) *NullableProduct202509EditProductRequestBodySkusListPrice {
	return &NullableProduct202509EditProductRequestBodySkusListPrice{value: val, isSet: true}
}

func (v NullableProduct202509EditProductRequestBodySkusListPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509EditProductRequestBodySkusListPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


