/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditProductRequestBodyProductAttributesValues type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditProductRequestBodyProductAttributesValues{}

// Product202509PartialEditProductRequestBodyProductAttributesValues struct for Product202509PartialEditProductRequestBodyProductAttributesValues
type Product202509PartialEditProductRequestBodyProductAttributesValues struct {
    // The ID of the product attribute value. This is either a built-in product attribute value ID from [Get Attributes API](https://partner.tiktokshop.com/docv2/page/6509c5784a0bb702c0561cc8) or a custom product attribute value ID returned after calling [Create Product API](https://partner.tiktokshop.com/docv2/page/6502fc8da57708028b42b18a).
    Id *string `json:"id,omitempty"`
    // A self-defined custom product attribute value if the existing values do not satisfy your needs. The system will auto-generate an ID after editing.  **Note**: - No duplicates allowed under the same attribute. - Max length: 2000 characters. 
    Name *string `json:"name,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditProductRequestBodyProductAttributesValues Product202509PartialEditProductRequestBodyProductAttributesValues

// NewProduct202509PartialEditProductRequestBodyProductAttributesValues instantiates a new Product202509PartialEditProductRequestBodyProductAttributesValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditProductRequestBodyProductAttributesValues() *Product202509PartialEditProductRequestBodyProductAttributesValues {
    this := Product202509PartialEditProductRequestBodyProductAttributesValues{}
    return &this
}

// NewProduct202509PartialEditProductRequestBodyProductAttributesValuesWithDefaults instantiates a new Product202509PartialEditProductRequestBodyProductAttributesValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditProductRequestBodyProductAttributesValuesWithDefaults() *Product202509PartialEditProductRequestBodyProductAttributesValues {
    this := Product202509PartialEditProductRequestBodyProductAttributesValues{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) SetId(v string) {
    o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) GetName() string {
    if o == nil || utils.IsNil(o.Name) {
        var ret string
        return ret
    }
    return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) GetNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Name) {
        return nil, false
    }
    return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) HasName() bool {
    if o != nil && !utils.IsNil(o.Name) {
        return true
    }

    return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) SetName(v string) {
    o.Name = &v
}

func (o Product202509PartialEditProductRequestBodyProductAttributesValues) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditProductRequestBodyProductAttributesValues) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Name) {
        toSerialize["name"] = o.Name
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditProductRequestBodyProductAttributesValues) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditProductRequestBodyProductAttributesValues := _Product202509PartialEditProductRequestBodyProductAttributesValues{}

    err = json.Unmarshal(data, &varProduct202509PartialEditProductRequestBodyProductAttributesValues)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditProductRequestBodyProductAttributesValues(varProduct202509PartialEditProductRequestBodyProductAttributesValues)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "id")
        delete(additionalProperties, "name")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditProductRequestBodyProductAttributesValues struct {
	value *Product202509PartialEditProductRequestBodyProductAttributesValues
	isSet bool
}

func (v NullableProduct202509PartialEditProductRequestBodyProductAttributesValues) Get() *Product202509PartialEditProductRequestBodyProductAttributesValues {
	return v.value
}

func (v *NullableProduct202509PartialEditProductRequestBodyProductAttributesValues) Set(val *Product202509PartialEditProductRequestBodyProductAttributesValues) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditProductRequestBodyProductAttributesValues) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditProductRequestBodyProductAttributesValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditProductRequestBodyProductAttributesValues(val *Product202509PartialEditProductRequestBodyProductAttributesValues) *NullableProduct202509PartialEditProductRequestBodyProductAttributesValues {
	return &NullableProduct202509PartialEditProductRequestBodyProductAttributesValues{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditProductRequestBodyProductAttributesValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditProductRequestBodyProductAttributesValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


