/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditGlobalProductRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditGlobalProductRequestBody{}

// Product202509PartialEditGlobalProductRequestBody struct for Product202509PartialEditGlobalProductRequestBody
type Product202509PartialEditGlobalProductRequestBody struct {
    // The ID of the brand of this product.  **Note**: Unauthorized brands won't be displayed on TikTok Shop.
    BrandId *string `json:"brand_id,omitempty"`
    // The ID of the category of this product.  - It must be a leaf category that corresponds to the category tree type specified in the `category_version` property.  - It must be a main category (`categories.permission_statuses=AVAILABLE` in [Get Global Categories API](650a03f8f1fd3102b91b338a)). **Note**: Refer to TikTok Shop Academy for information on product category restrictions.
    CategoryId *string `json:"category_id,omitempty"`
    // The category tree version to assign this product to. Possible values based on region: - US: `v2`, represents the 7-level category tree.   **Important**: If the seller account contains an active US shop, you must pass `v2` when using this API. - Other regions: `v1`, represents the 3-level category tree. Default: `v1`
    CategoryVersion *string `json:"category_version,omitempty"`
    // The list of certifications for your product. Max count: 10  As per TikTok Shop guidelines, certifications are required for certain restricted product categories. Retrieve the certification requirements for your product from the  [Get Global Category Rules API](https://partner.tiktokshop.com/docv2/page/650a056df1fd3102b91b5b8e). Refer to [TikTok Shop Restricted Products Policy](https://seller-us.tiktok.com/university/essay?identity=1&role=1&knowledge_id=3238037484275457&from=policy) for information on product category restrictions.
    Certifications []Product202509PartialEditGlobalProductRequestBodyCertifications `json:"certifications,omitempty"`
    // The product description in HTML format.  **Note**: - The content must conform to the [HTML syntax](https://html.spec.whatwg.org/). All HTML tags are accepted but to optimize display on the TikTok Shop product detail page, the system will automatically convert certain tags into alternative formats, such as rendering `<table>` tags as images. - Max length: 10,000 characters. - Image guidelines: You must use [TikTok Shop image URLs](6509df95defece02be598a22). Max 30 `<img>` tags, each under 4000px with `src`, `width`, and `height` attributes.  **Recommendations**:  - If you are syncing a pre-existing description from another platform, include the full HTML source description here. - Provide a detailed description, ideally over 300 characters. - Include 3-5 key selling points, each under 250 characters, with supporting images. - Use 1600x1600 px for the image dimensions.
    Description *string `json:"description,omitempty"`
    // An external identifier used in an external ecommerce platform. This is used to associate the global product between TikTok Shop and the external ecommerce platform.  Max length: 999 characters
    ExternalGlobalProductId *string `json:"external_global_product_id,omitempty"`
    // A list of images to display in the product image gallery. - Max count: 9 - Arrange your image URIs in the sequence that they should appear on TikTok Shop. - Image dimensions: [300x300 px, 4000x4000 px]    **Recommendations**: - Use a minimum of 5 images. - The first image should have a white background. Use the [Optimize Images API](https://partner.tiktokshop.com/docv2/page/665692b35d39dc02deb49a97) to change the background to white.
    MainImages []Product202509PartialEditGlobalProductRequestBodyMainImages `json:"main_images,omitempty"`
    Manufacturer *Product202509PartialEditGlobalProductRequestBodyManufacturer `json:"manufacturer,omitempty"`
    // A comma-delimited list of manufacturer IDs. Retrieve the IDs from the [Search Manufacturers API](67066a580dcee902fa03ccf9). Default: The IDs provided when the global product was created.  **Note**: Applicable only for the EU market in certain categories. Use the [Get Global Category Rules API](650a056df1fd3102b91b5b8e) to check the requirements.
    ManufacturerIds []string `json:"manufacturer_ids,omitempty"`
    PackageDimensions *Product202509PartialEditGlobalProductRequestBodyPackageDimensions `json:"package_dimensions,omitempty"`
    PackageWeight *Product202509PartialEditGlobalProductRequestBodyPackageWeight `json:"package_weight,omitempty"`
    // A list of general attributes (e.g. manufacturer, country of origin, materials used) that describe the product as a whole, regardless of variant.  **Important**: The attributes available for use are determined by the system based on the product's assigned category, with some being mandatory. You must provide the product attributes marked as `is_required` in the response of the [Get Global Attributes API](650a0483c16ffe02b8dfc80a).
    ProductAttributes []Product202509PartialEditGlobalProductRequestBodyProductAttributes `json:"product_attributes,omitempty"`
    // A comma-delimited list of responsible person IDs. Retrieve the IDs from the [Search Responsible Persons API](67066a55f17b7d02f95d2fb1). Default: The IDs provided when the global product was created.  **Note**: Applicable only for the EU market in certain categories. Use the [Get Global Category Rules API](650a056df1fd3102b91b5b8e) to check the requirements.
    ResponsiblePersonIds []string `json:"responsible_person_ids,omitempty"`
    SizeChart *Product202509PartialEditGlobalProductRequestBodySizeChart `json:"size_chart,omitempty"`
    // A list of global Stock Keeping Units (SKUs) used to identify distinct variants of the product.  **Note**: - Max SKUs for EU, JP, UK, US: 300 - Max SKUs for other regions: 100  **Recommendations**: Place the most important variant at the beginning of the array.
    Skus []Product202509PartialEditGlobalProductRequestBodySkus `json:"skus,omitempty"`
    // The product title.  Title length: - DE, ES, FR, IE, IT, JP, UK, US: [1, 255]  - MX:[1,300]  - Other regions: [25, 255]
    Title *string `json:"title,omitempty"`
    Video *Product202509PartialEditGlobalProductRequestBodyVideo `json:"video,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditGlobalProductRequestBody Product202509PartialEditGlobalProductRequestBody

// NewProduct202509PartialEditGlobalProductRequestBody instantiates a new Product202509PartialEditGlobalProductRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditGlobalProductRequestBody() *Product202509PartialEditGlobalProductRequestBody {
    this := Product202509PartialEditGlobalProductRequestBody{}
    return &this
}

// NewProduct202509PartialEditGlobalProductRequestBodyWithDefaults instantiates a new Product202509PartialEditGlobalProductRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditGlobalProductRequestBodyWithDefaults() *Product202509PartialEditGlobalProductRequestBody {
    this := Product202509PartialEditGlobalProductRequestBody{}
    return &this
}

// GetBrandId returns the BrandId field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetBrandId() string {
    if o == nil || utils.IsNil(o.BrandId) {
        var ret string
        return ret
    }
    return *o.BrandId
}

// GetBrandIdOk returns a tuple with the BrandId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetBrandIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.BrandId) {
        return nil, false
    }
    return o.BrandId, true
}

// HasBrandId returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasBrandId() bool {
    if o != nil && !utils.IsNil(o.BrandId) {
        return true
    }

    return false
}

// SetBrandId gets a reference to the given string and assigns it to the BrandId field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetBrandId(v string) {
    o.BrandId = &v
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetCategoryId() string {
    if o == nil || utils.IsNil(o.CategoryId) {
        var ret string
        return ret
    }
    return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetCategoryIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CategoryId) {
        return nil, false
    }
    return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasCategoryId() bool {
    if o != nil && !utils.IsNil(o.CategoryId) {
        return true
    }

    return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetCategoryId(v string) {
    o.CategoryId = &v
}

// GetCategoryVersion returns the CategoryVersion field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetCategoryVersion() string {
    if o == nil || utils.IsNil(o.CategoryVersion) {
        var ret string
        return ret
    }
    return *o.CategoryVersion
}

// GetCategoryVersionOk returns a tuple with the CategoryVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetCategoryVersionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CategoryVersion) {
        return nil, false
    }
    return o.CategoryVersion, true
}

// HasCategoryVersion returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasCategoryVersion() bool {
    if o != nil && !utils.IsNil(o.CategoryVersion) {
        return true
    }

    return false
}

// SetCategoryVersion gets a reference to the given string and assigns it to the CategoryVersion field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetCategoryVersion(v string) {
    o.CategoryVersion = &v
}

// GetCertifications returns the Certifications field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetCertifications() []Product202509PartialEditGlobalProductRequestBodyCertifications {
    if o == nil || utils.IsNil(o.Certifications) {
        var ret []Product202509PartialEditGlobalProductRequestBodyCertifications
        return ret
    }
    return o.Certifications
}

// GetCertificationsOk returns a tuple with the Certifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetCertificationsOk() ([]Product202509PartialEditGlobalProductRequestBodyCertifications, bool) {
    if o == nil || utils.IsNil(o.Certifications) {
        return nil, false
    }
    return o.Certifications, true
}

// HasCertifications returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasCertifications() bool {
    if o != nil && !utils.IsNil(o.Certifications) {
        return true
    }

    return false
}

// SetCertifications gets a reference to the given []Product202509PartialEditGlobalProductRequestBodyCertifications and assigns it to the Certifications field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetCertifications(v []Product202509PartialEditGlobalProductRequestBodyCertifications) {
    o.Certifications = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetDescription() string {
    if o == nil || utils.IsNil(o.Description) {
        var ret string
        return ret
    }
    return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetDescriptionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Description) {
        return nil, false
    }
    return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasDescription() bool {
    if o != nil && !utils.IsNil(o.Description) {
        return true
    }

    return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetDescription(v string) {
    o.Description = &v
}

// GetExternalGlobalProductId returns the ExternalGlobalProductId field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetExternalGlobalProductId() string {
    if o == nil || utils.IsNil(o.ExternalGlobalProductId) {
        var ret string
        return ret
    }
    return *o.ExternalGlobalProductId
}

// GetExternalGlobalProductIdOk returns a tuple with the ExternalGlobalProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetExternalGlobalProductIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ExternalGlobalProductId) {
        return nil, false
    }
    return o.ExternalGlobalProductId, true
}

// HasExternalGlobalProductId returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasExternalGlobalProductId() bool {
    if o != nil && !utils.IsNil(o.ExternalGlobalProductId) {
        return true
    }

    return false
}

// SetExternalGlobalProductId gets a reference to the given string and assigns it to the ExternalGlobalProductId field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetExternalGlobalProductId(v string) {
    o.ExternalGlobalProductId = &v
}

// GetMainImages returns the MainImages field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetMainImages() []Product202509PartialEditGlobalProductRequestBodyMainImages {
    if o == nil || utils.IsNil(o.MainImages) {
        var ret []Product202509PartialEditGlobalProductRequestBodyMainImages
        return ret
    }
    return o.MainImages
}

// GetMainImagesOk returns a tuple with the MainImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetMainImagesOk() ([]Product202509PartialEditGlobalProductRequestBodyMainImages, bool) {
    if o == nil || utils.IsNil(o.MainImages) {
        return nil, false
    }
    return o.MainImages, true
}

// HasMainImages returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasMainImages() bool {
    if o != nil && !utils.IsNil(o.MainImages) {
        return true
    }

    return false
}

// SetMainImages gets a reference to the given []Product202509PartialEditGlobalProductRequestBodyMainImages and assigns it to the MainImages field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetMainImages(v []Product202509PartialEditGlobalProductRequestBodyMainImages) {
    o.MainImages = v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetManufacturer() Product202509PartialEditGlobalProductRequestBodyManufacturer {
    if o == nil || utils.IsNil(o.Manufacturer) {
        var ret Product202509PartialEditGlobalProductRequestBodyManufacturer
        return ret
    }
    return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetManufacturerOk() (*Product202509PartialEditGlobalProductRequestBodyManufacturer, bool) {
    if o == nil || utils.IsNil(o.Manufacturer) {
        return nil, false
    }
    return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasManufacturer() bool {
    if o != nil && !utils.IsNil(o.Manufacturer) {
        return true
    }

    return false
}

// SetManufacturer gets a reference to the given Product202509PartialEditGlobalProductRequestBodyManufacturer and assigns it to the Manufacturer field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetManufacturer(v Product202509PartialEditGlobalProductRequestBodyManufacturer) {
    o.Manufacturer = &v
}

// GetManufacturerIds returns the ManufacturerIds field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetManufacturerIds() []string {
    if o == nil || utils.IsNil(o.ManufacturerIds) {
        var ret []string
        return ret
    }
    return o.ManufacturerIds
}

// GetManufacturerIdsOk returns a tuple with the ManufacturerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetManufacturerIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.ManufacturerIds) {
        return nil, false
    }
    return o.ManufacturerIds, true
}

// HasManufacturerIds returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasManufacturerIds() bool {
    if o != nil && !utils.IsNil(o.ManufacturerIds) {
        return true
    }

    return false
}

// SetManufacturerIds gets a reference to the given []string and assigns it to the ManufacturerIds field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetManufacturerIds(v []string) {
    o.ManufacturerIds = v
}

// GetPackageDimensions returns the PackageDimensions field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetPackageDimensions() Product202509PartialEditGlobalProductRequestBodyPackageDimensions {
    if o == nil || utils.IsNil(o.PackageDimensions) {
        var ret Product202509PartialEditGlobalProductRequestBodyPackageDimensions
        return ret
    }
    return *o.PackageDimensions
}

// GetPackageDimensionsOk returns a tuple with the PackageDimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetPackageDimensionsOk() (*Product202509PartialEditGlobalProductRequestBodyPackageDimensions, bool) {
    if o == nil || utils.IsNil(o.PackageDimensions) {
        return nil, false
    }
    return o.PackageDimensions, true
}

// HasPackageDimensions returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasPackageDimensions() bool {
    if o != nil && !utils.IsNil(o.PackageDimensions) {
        return true
    }

    return false
}

// SetPackageDimensions gets a reference to the given Product202509PartialEditGlobalProductRequestBodyPackageDimensions and assigns it to the PackageDimensions field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetPackageDimensions(v Product202509PartialEditGlobalProductRequestBodyPackageDimensions) {
    o.PackageDimensions = &v
}

// GetPackageWeight returns the PackageWeight field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetPackageWeight() Product202509PartialEditGlobalProductRequestBodyPackageWeight {
    if o == nil || utils.IsNil(o.PackageWeight) {
        var ret Product202509PartialEditGlobalProductRequestBodyPackageWeight
        return ret
    }
    return *o.PackageWeight
}

// GetPackageWeightOk returns a tuple with the PackageWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetPackageWeightOk() (*Product202509PartialEditGlobalProductRequestBodyPackageWeight, bool) {
    if o == nil || utils.IsNil(o.PackageWeight) {
        return nil, false
    }
    return o.PackageWeight, true
}

// HasPackageWeight returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasPackageWeight() bool {
    if o != nil && !utils.IsNil(o.PackageWeight) {
        return true
    }

    return false
}

// SetPackageWeight gets a reference to the given Product202509PartialEditGlobalProductRequestBodyPackageWeight and assigns it to the PackageWeight field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetPackageWeight(v Product202509PartialEditGlobalProductRequestBodyPackageWeight) {
    o.PackageWeight = &v
}

// GetProductAttributes returns the ProductAttributes field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetProductAttributes() []Product202509PartialEditGlobalProductRequestBodyProductAttributes {
    if o == nil || utils.IsNil(o.ProductAttributes) {
        var ret []Product202509PartialEditGlobalProductRequestBodyProductAttributes
        return ret
    }
    return o.ProductAttributes
}

// GetProductAttributesOk returns a tuple with the ProductAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetProductAttributesOk() ([]Product202509PartialEditGlobalProductRequestBodyProductAttributes, bool) {
    if o == nil || utils.IsNil(o.ProductAttributes) {
        return nil, false
    }
    return o.ProductAttributes, true
}

// HasProductAttributes returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasProductAttributes() bool {
    if o != nil && !utils.IsNil(o.ProductAttributes) {
        return true
    }

    return false
}

// SetProductAttributes gets a reference to the given []Product202509PartialEditGlobalProductRequestBodyProductAttributes and assigns it to the ProductAttributes field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetProductAttributes(v []Product202509PartialEditGlobalProductRequestBodyProductAttributes) {
    o.ProductAttributes = v
}

// GetResponsiblePersonIds returns the ResponsiblePersonIds field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetResponsiblePersonIds() []string {
    if o == nil || utils.IsNil(o.ResponsiblePersonIds) {
        var ret []string
        return ret
    }
    return o.ResponsiblePersonIds
}

// GetResponsiblePersonIdsOk returns a tuple with the ResponsiblePersonIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetResponsiblePersonIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.ResponsiblePersonIds) {
        return nil, false
    }
    return o.ResponsiblePersonIds, true
}

// HasResponsiblePersonIds returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasResponsiblePersonIds() bool {
    if o != nil && !utils.IsNil(o.ResponsiblePersonIds) {
        return true
    }

    return false
}

// SetResponsiblePersonIds gets a reference to the given []string and assigns it to the ResponsiblePersonIds field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetResponsiblePersonIds(v []string) {
    o.ResponsiblePersonIds = v
}

// GetSizeChart returns the SizeChart field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetSizeChart() Product202509PartialEditGlobalProductRequestBodySizeChart {
    if o == nil || utils.IsNil(o.SizeChart) {
        var ret Product202509PartialEditGlobalProductRequestBodySizeChart
        return ret
    }
    return *o.SizeChart
}

// GetSizeChartOk returns a tuple with the SizeChart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetSizeChartOk() (*Product202509PartialEditGlobalProductRequestBodySizeChart, bool) {
    if o == nil || utils.IsNil(o.SizeChart) {
        return nil, false
    }
    return o.SizeChart, true
}

// HasSizeChart returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasSizeChart() bool {
    if o != nil && !utils.IsNil(o.SizeChart) {
        return true
    }

    return false
}

// SetSizeChart gets a reference to the given Product202509PartialEditGlobalProductRequestBodySizeChart and assigns it to the SizeChart field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetSizeChart(v Product202509PartialEditGlobalProductRequestBodySizeChart) {
    o.SizeChart = &v
}

// GetSkus returns the Skus field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetSkus() []Product202509PartialEditGlobalProductRequestBodySkus {
    if o == nil || utils.IsNil(o.Skus) {
        var ret []Product202509PartialEditGlobalProductRequestBodySkus
        return ret
    }
    return o.Skus
}

// GetSkusOk returns a tuple with the Skus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetSkusOk() ([]Product202509PartialEditGlobalProductRequestBodySkus, bool) {
    if o == nil || utils.IsNil(o.Skus) {
        return nil, false
    }
    return o.Skus, true
}

// HasSkus returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasSkus() bool {
    if o != nil && !utils.IsNil(o.Skus) {
        return true
    }

    return false
}

// SetSkus gets a reference to the given []Product202509PartialEditGlobalProductRequestBodySkus and assigns it to the Skus field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetSkus(v []Product202509PartialEditGlobalProductRequestBodySkus) {
    o.Skus = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetTitle() string {
    if o == nil || utils.IsNil(o.Title) {
        var ret string
        return ret
    }
    return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetTitleOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Title) {
        return nil, false
    }
    return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasTitle() bool {
    if o != nil && !utils.IsNil(o.Title) {
        return true
    }

    return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetTitle(v string) {
    o.Title = &v
}

// GetVideo returns the Video field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBody) GetVideo() Product202509PartialEditGlobalProductRequestBodyVideo {
    if o == nil || utils.IsNil(o.Video) {
        var ret Product202509PartialEditGlobalProductRequestBodyVideo
        return ret
    }
    return *o.Video
}

// GetVideoOk returns a tuple with the Video field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) GetVideoOk() (*Product202509PartialEditGlobalProductRequestBodyVideo, bool) {
    if o == nil || utils.IsNil(o.Video) {
        return nil, false
    }
    return o.Video, true
}

// HasVideo returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBody) HasVideo() bool {
    if o != nil && !utils.IsNil(o.Video) {
        return true
    }

    return false
}

// SetVideo gets a reference to the given Product202509PartialEditGlobalProductRequestBodyVideo and assigns it to the Video field.
func (o *Product202509PartialEditGlobalProductRequestBody) SetVideo(v Product202509PartialEditGlobalProductRequestBodyVideo) {
    o.Video = &v
}

func (o Product202509PartialEditGlobalProductRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditGlobalProductRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.BrandId) {
        toSerialize["brand_id"] = o.BrandId
    }
    if !utils.IsNil(o.CategoryId) {
        toSerialize["category_id"] = o.CategoryId
    }
    if !utils.IsNil(o.CategoryVersion) {
        toSerialize["category_version"] = o.CategoryVersion
    }
    if !utils.IsNil(o.Certifications) {
        toSerialize["certifications"] = o.Certifications
    }
    if !utils.IsNil(o.Description) {
        toSerialize["description"] = o.Description
    }
    if !utils.IsNil(o.ExternalGlobalProductId) {
        toSerialize["external_global_product_id"] = o.ExternalGlobalProductId
    }
    if !utils.IsNil(o.MainImages) {
        toSerialize["main_images"] = o.MainImages
    }
    if !utils.IsNil(o.Manufacturer) {
        toSerialize["manufacturer"] = o.Manufacturer
    }
    if !utils.IsNil(o.ManufacturerIds) {
        toSerialize["manufacturer_ids"] = o.ManufacturerIds
    }
    if !utils.IsNil(o.PackageDimensions) {
        toSerialize["package_dimensions"] = o.PackageDimensions
    }
    if !utils.IsNil(o.PackageWeight) {
        toSerialize["package_weight"] = o.PackageWeight
    }
    if !utils.IsNil(o.ProductAttributes) {
        toSerialize["product_attributes"] = o.ProductAttributes
    }
    if !utils.IsNil(o.ResponsiblePersonIds) {
        toSerialize["responsible_person_ids"] = o.ResponsiblePersonIds
    }
    if !utils.IsNil(o.SizeChart) {
        toSerialize["size_chart"] = o.SizeChart
    }
    if !utils.IsNil(o.Skus) {
        toSerialize["skus"] = o.Skus
    }
    if !utils.IsNil(o.Title) {
        toSerialize["title"] = o.Title
    }
    if !utils.IsNil(o.Video) {
        toSerialize["video"] = o.Video
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditGlobalProductRequestBody) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditGlobalProductRequestBody := _Product202509PartialEditGlobalProductRequestBody{}

    err = json.Unmarshal(data, &varProduct202509PartialEditGlobalProductRequestBody)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditGlobalProductRequestBody(varProduct202509PartialEditGlobalProductRequestBody)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "brand_id")
        delete(additionalProperties, "category_id")
        delete(additionalProperties, "category_version")
        delete(additionalProperties, "certifications")
        delete(additionalProperties, "description")
        delete(additionalProperties, "external_global_product_id")
        delete(additionalProperties, "main_images")
        delete(additionalProperties, "manufacturer")
        delete(additionalProperties, "manufacturer_ids")
        delete(additionalProperties, "package_dimensions")
        delete(additionalProperties, "package_weight")
        delete(additionalProperties, "product_attributes")
        delete(additionalProperties, "responsible_person_ids")
        delete(additionalProperties, "size_chart")
        delete(additionalProperties, "skus")
        delete(additionalProperties, "title")
        delete(additionalProperties, "video")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditGlobalProductRequestBody struct {
	value *Product202509PartialEditGlobalProductRequestBody
	isSet bool
}

func (v NullableProduct202509PartialEditGlobalProductRequestBody) Get() *Product202509PartialEditGlobalProductRequestBody {
	return v.value
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBody) Set(val *Product202509PartialEditGlobalProductRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditGlobalProductRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditGlobalProductRequestBody(val *Product202509PartialEditGlobalProductRequestBody) *NullableProduct202509PartialEditGlobalProductRequestBody {
	return &NullableProduct202509PartialEditGlobalProductRequestBody{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditGlobalProductRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


