/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg{}

// Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg struct for Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg
type Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg struct {
    // The URI of the image. Obtain this URI by uploading the images through the [Upload Product Image API](6509df95defece02be598a22)  with `use_case=ATTRIBUTE_IMAGE`. 
    Uri *string `json:"uri,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg

// NewProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg instantiates a new Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg() *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg {
    this := Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg{}
    return &this
}

// NewProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImgWithDefaults instantiates a new Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImgWithDefaults() *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg {
    this := Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg{}
    return &this
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) GetUri() string {
    if o == nil || utils.IsNil(o.Uri) {
        var ret string
        return ret
    }
    return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) GetUriOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Uri) {
        return nil, false
    }
    return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) HasUri() bool {
    if o != nil && !utils.IsNil(o.Uri) {
        return true
    }

    return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) SetUri(v string) {
    o.Uri = &v
}

func (o Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Uri) {
        toSerialize["uri"] = o.Uri
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg := _Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg{}

    err = json.Unmarshal(data, &varProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg(varProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "uri")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg struct {
	value *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg
	isSet bool
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) Get() *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg {
	return v.value
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) Set(val *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg(val *Product202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) *NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg {
	return &NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodySkusSalesAttributesSkuImg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


