/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditProductRequestBodySkusPrice type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditProductRequestBodySkusPrice{}

// Product202509PartialEditProductRequestBodySkusPrice struct for Product202509PartialEditProductRequestBodySkusPrice
type Product202509PartialEditProductRequestBodySkusPrice struct {
    // **Local sellers/Intra-EU sellers** The SKU's **local display price** shown on the product page before any discounts. Refer to [Product Pricing](https://partner.tiktokshop.com/docv2/page/67e1288d76cfee049d9af858) for the allowed price ranges in each market.
    Amount *string `json:"amount,omitempty"`
    // The currency. Possible values based on the region: - BRL: Brazil - EUR: France, Germany, Ireland, Italy, Spain - GBP: United Kingdom - IDR: Indonesia - JPY: Japan - MXN: Mexico - MYR: Malaysia - PHP: Philippines - SGD: Singapore - THB: Thailand - USD: United States - VND: Vietnam
    Currency *string `json:"currency,omitempty"`
    // **Global sellers** The SKU's **local display price** shown on the product page before any discounts.  Refer to [Product Pricing](https://partner.tiktokshop.com/docv2/page/67e1288d76cfee049d9af858) for the allowed price ranges in each market.  **Note**:  - Applicable for all global sellers. - Required for JP and US shops using China warehouses. Optional for others. - This is the definitive final price shown on the product page, all other prices will be ignored.
    SalePrice *string `json:"sale_price,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditProductRequestBodySkusPrice Product202509PartialEditProductRequestBodySkusPrice

// NewProduct202509PartialEditProductRequestBodySkusPrice instantiates a new Product202509PartialEditProductRequestBodySkusPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditProductRequestBodySkusPrice() *Product202509PartialEditProductRequestBodySkusPrice {
    this := Product202509PartialEditProductRequestBodySkusPrice{}
    return &this
}

// NewProduct202509PartialEditProductRequestBodySkusPriceWithDefaults instantiates a new Product202509PartialEditProductRequestBodySkusPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditProductRequestBodySkusPriceWithDefaults() *Product202509PartialEditProductRequestBodySkusPrice {
    this := Product202509PartialEditProductRequestBodySkusPrice{}
    return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkusPrice) GetAmount() string {
    if o == nil || utils.IsNil(o.Amount) {
        var ret string
        return ret
    }
    return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkusPrice) GetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Amount) {
        return nil, false
    }
    return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkusPrice) HasAmount() bool {
    if o != nil && !utils.IsNil(o.Amount) {
        return true
    }

    return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *Product202509PartialEditProductRequestBodySkusPrice) SetAmount(v string) {
    o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkusPrice) GetCurrency() string {
    if o == nil || utils.IsNil(o.Currency) {
        var ret string
        return ret
    }
    return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkusPrice) GetCurrencyOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Currency) {
        return nil, false
    }
    return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkusPrice) HasCurrency() bool {
    if o != nil && !utils.IsNil(o.Currency) {
        return true
    }

    return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Product202509PartialEditProductRequestBodySkusPrice) SetCurrency(v string) {
    o.Currency = &v
}

// GetSalePrice returns the SalePrice field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkusPrice) GetSalePrice() string {
    if o == nil || utils.IsNil(o.SalePrice) {
        var ret string
        return ret
    }
    return *o.SalePrice
}

// GetSalePriceOk returns a tuple with the SalePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkusPrice) GetSalePriceOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SalePrice) {
        return nil, false
    }
    return o.SalePrice, true
}

// HasSalePrice returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkusPrice) HasSalePrice() bool {
    if o != nil && !utils.IsNil(o.SalePrice) {
        return true
    }

    return false
}

// SetSalePrice gets a reference to the given string and assigns it to the SalePrice field.
func (o *Product202509PartialEditProductRequestBodySkusPrice) SetSalePrice(v string) {
    o.SalePrice = &v
}

func (o Product202509PartialEditProductRequestBodySkusPrice) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditProductRequestBodySkusPrice) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Amount) {
        toSerialize["amount"] = o.Amount
    }
    if !utils.IsNil(o.Currency) {
        toSerialize["currency"] = o.Currency
    }
    if !utils.IsNil(o.SalePrice) {
        toSerialize["sale_price"] = o.SalePrice
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditProductRequestBodySkusPrice) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditProductRequestBodySkusPrice := _Product202509PartialEditProductRequestBodySkusPrice{}

    err = json.Unmarshal(data, &varProduct202509PartialEditProductRequestBodySkusPrice)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditProductRequestBodySkusPrice(varProduct202509PartialEditProductRequestBodySkusPrice)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "amount")
        delete(additionalProperties, "currency")
        delete(additionalProperties, "sale_price")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditProductRequestBodySkusPrice struct {
	value *Product202509PartialEditProductRequestBodySkusPrice
	isSet bool
}

func (v NullableProduct202509PartialEditProductRequestBodySkusPrice) Get() *Product202509PartialEditProductRequestBodySkusPrice {
	return v.value
}

func (v *NullableProduct202509PartialEditProductRequestBodySkusPrice) Set(val *Product202509PartialEditProductRequestBodySkusPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditProductRequestBodySkusPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditProductRequestBodySkusPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditProductRequestBodySkusPrice(val *Product202509PartialEditProductRequestBodySkusPrice) *NullableProduct202509PartialEditProductRequestBodySkusPrice {
	return &NullableProduct202509PartialEditProductRequestBodySkusPrice{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditProductRequestBodySkusPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditProductRequestBodySkusPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


