/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditProductResponseDataSkus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditProductResponseDataSkus{}

// Product202509PartialEditProductResponseDataSkus struct for Product202509PartialEditProductResponseDataSkus
type Product202509PartialEditProductResponseDataSkus struct {
    // An external identifier used in an external ecommerce platform. This is used to associate the SKU between TikTok Shop and the external ecommerce platform. 
    ExternalSkuId *string `json:"external_sku_id,omitempty"`
    // The fees required for this product based on TikTok Shop policies. Fees are required only for certain product categories, retrieve the requirements from the [Get Category Rules API](https://partner.tiktokshop.com/docv2/page/6509c0febace3e02b74594a9). 
    Fees []Product202509PartialEditProductResponseDataSkusFees `json:"fees,omitempty"`
    // The SKU ID generated by TikTok Shop. One product can contain multiple SKU IDs.
    Id *string `json:"id,omitempty"`
    // A list of attributes  (e.g. size, color, length) that define each variant of a product.
    SalesAttributes []Product202509PartialEditProductResponseDataSkusSalesAttributes `json:"sales_attributes,omitempty"`
    // An internal code/name for managing SKUs, not visible to buyers.  
    SellerSku *string `json:"seller_sku,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditProductResponseDataSkus Product202509PartialEditProductResponseDataSkus

// NewProduct202509PartialEditProductResponseDataSkus instantiates a new Product202509PartialEditProductResponseDataSkus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditProductResponseDataSkus() *Product202509PartialEditProductResponseDataSkus {
    this := Product202509PartialEditProductResponseDataSkus{}
    return &this
}

// NewProduct202509PartialEditProductResponseDataSkusWithDefaults instantiates a new Product202509PartialEditProductResponseDataSkus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditProductResponseDataSkusWithDefaults() *Product202509PartialEditProductResponseDataSkus {
    this := Product202509PartialEditProductResponseDataSkus{}
    return &this
}

// GetExternalSkuId returns the ExternalSkuId field value if set, zero value otherwise.
func (o *Product202509PartialEditProductResponseDataSkus) GetExternalSkuId() string {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        var ret string
        return ret
    }
    return *o.ExternalSkuId
}

// GetExternalSkuIdOk returns a tuple with the ExternalSkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductResponseDataSkus) GetExternalSkuIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        return nil, false
    }
    return o.ExternalSkuId, true
}

// HasExternalSkuId returns a boolean if a field has been set.
func (o *Product202509PartialEditProductResponseDataSkus) HasExternalSkuId() bool {
    if o != nil && !utils.IsNil(o.ExternalSkuId) {
        return true
    }

    return false
}

// SetExternalSkuId gets a reference to the given string and assigns it to the ExternalSkuId field.
func (o *Product202509PartialEditProductResponseDataSkus) SetExternalSkuId(v string) {
    o.ExternalSkuId = &v
}

// GetFees returns the Fees field value if set, zero value otherwise.
func (o *Product202509PartialEditProductResponseDataSkus) GetFees() []Product202509PartialEditProductResponseDataSkusFees {
    if o == nil || utils.IsNil(o.Fees) {
        var ret []Product202509PartialEditProductResponseDataSkusFees
        return ret
    }
    return o.Fees
}

// GetFeesOk returns a tuple with the Fees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductResponseDataSkus) GetFeesOk() ([]Product202509PartialEditProductResponseDataSkusFees, bool) {
    if o == nil || utils.IsNil(o.Fees) {
        return nil, false
    }
    return o.Fees, true
}

// HasFees returns a boolean if a field has been set.
func (o *Product202509PartialEditProductResponseDataSkus) HasFees() bool {
    if o != nil && !utils.IsNil(o.Fees) {
        return true
    }

    return false
}

// SetFees gets a reference to the given []Product202509PartialEditProductResponseDataSkusFees and assigns it to the Fees field.
func (o *Product202509PartialEditProductResponseDataSkus) SetFees(v []Product202509PartialEditProductResponseDataSkusFees) {
    o.Fees = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509PartialEditProductResponseDataSkus) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductResponseDataSkus) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509PartialEditProductResponseDataSkus) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509PartialEditProductResponseDataSkus) SetId(v string) {
    o.Id = &v
}

// GetSalesAttributes returns the SalesAttributes field value if set, zero value otherwise.
func (o *Product202509PartialEditProductResponseDataSkus) GetSalesAttributes() []Product202509PartialEditProductResponseDataSkusSalesAttributes {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        var ret []Product202509PartialEditProductResponseDataSkusSalesAttributes
        return ret
    }
    return o.SalesAttributes
}

// GetSalesAttributesOk returns a tuple with the SalesAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductResponseDataSkus) GetSalesAttributesOk() ([]Product202509PartialEditProductResponseDataSkusSalesAttributes, bool) {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        return nil, false
    }
    return o.SalesAttributes, true
}

// HasSalesAttributes returns a boolean if a field has been set.
func (o *Product202509PartialEditProductResponseDataSkus) HasSalesAttributes() bool {
    if o != nil && !utils.IsNil(o.SalesAttributes) {
        return true
    }

    return false
}

// SetSalesAttributes gets a reference to the given []Product202509PartialEditProductResponseDataSkusSalesAttributes and assigns it to the SalesAttributes field.
func (o *Product202509PartialEditProductResponseDataSkus) SetSalesAttributes(v []Product202509PartialEditProductResponseDataSkusSalesAttributes) {
    o.SalesAttributes = v
}

// GetSellerSku returns the SellerSku field value if set, zero value otherwise.
func (o *Product202509PartialEditProductResponseDataSkus) GetSellerSku() string {
    if o == nil || utils.IsNil(o.SellerSku) {
        var ret string
        return ret
    }
    return *o.SellerSku
}

// GetSellerSkuOk returns a tuple with the SellerSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductResponseDataSkus) GetSellerSkuOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerSku) {
        return nil, false
    }
    return o.SellerSku, true
}

// HasSellerSku returns a boolean if a field has been set.
func (o *Product202509PartialEditProductResponseDataSkus) HasSellerSku() bool {
    if o != nil && !utils.IsNil(o.SellerSku) {
        return true
    }

    return false
}

// SetSellerSku gets a reference to the given string and assigns it to the SellerSku field.
func (o *Product202509PartialEditProductResponseDataSkus) SetSellerSku(v string) {
    o.SellerSku = &v
}

func (o Product202509PartialEditProductResponseDataSkus) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditProductResponseDataSkus) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ExternalSkuId) {
        toSerialize["external_sku_id"] = o.ExternalSkuId
    }
    if !utils.IsNil(o.Fees) {
        toSerialize["fees"] = o.Fees
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.SalesAttributes) {
        toSerialize["sales_attributes"] = o.SalesAttributes
    }
    if !utils.IsNil(o.SellerSku) {
        toSerialize["seller_sku"] = o.SellerSku
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditProductResponseDataSkus) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditProductResponseDataSkus := _Product202509PartialEditProductResponseDataSkus{}

    err = json.Unmarshal(data, &varProduct202509PartialEditProductResponseDataSkus)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditProductResponseDataSkus(varProduct202509PartialEditProductResponseDataSkus)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "external_sku_id")
        delete(additionalProperties, "fees")
        delete(additionalProperties, "id")
        delete(additionalProperties, "sales_attributes")
        delete(additionalProperties, "seller_sku")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditProductResponseDataSkus struct {
	value *Product202509PartialEditProductResponseDataSkus
	isSet bool
}

func (v NullableProduct202509PartialEditProductResponseDataSkus) Get() *Product202509PartialEditProductResponseDataSkus {
	return v.value
}

func (v *NullableProduct202509PartialEditProductResponseDataSkus) Set(val *Product202509PartialEditProductResponseDataSkus) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditProductResponseDataSkus) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditProductResponseDataSkus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditProductResponseDataSkus(val *Product202509PartialEditProductResponseDataSkus) *NullableProduct202509PartialEditProductResponseDataSkus {
	return &NullableProduct202509PartialEditProductResponseDataSkus{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditProductResponseDataSkus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditProductResponseDataSkus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


