/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditGlobalProductRequestBodyPackageWeight type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditGlobalProductRequestBodyPackageWeight{}

// Product202509PartialEditGlobalProductRequestBodyPackageWeight struct for Product202509PartialEditGlobalProductRequestBodyPackageWeight
type Product202509PartialEditGlobalProductRequestBodyPackageWeight struct {
    // The unit for the package weight. Only `KILOGRAM` is supported.
    Unit *string `json:"unit,omitempty"`
    // The package weight, which must be a positive number with up to 3 decimal places.
    Value *string `json:"value,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditGlobalProductRequestBodyPackageWeight Product202509PartialEditGlobalProductRequestBodyPackageWeight

// NewProduct202509PartialEditGlobalProductRequestBodyPackageWeight instantiates a new Product202509PartialEditGlobalProductRequestBodyPackageWeight object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditGlobalProductRequestBodyPackageWeight() *Product202509PartialEditGlobalProductRequestBodyPackageWeight {
    this := Product202509PartialEditGlobalProductRequestBodyPackageWeight{}
    return &this
}

// NewProduct202509PartialEditGlobalProductRequestBodyPackageWeightWithDefaults instantiates a new Product202509PartialEditGlobalProductRequestBodyPackageWeight object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditGlobalProductRequestBodyPackageWeightWithDefaults() *Product202509PartialEditGlobalProductRequestBodyPackageWeight {
    this := Product202509PartialEditGlobalProductRequestBodyPackageWeight{}
    return &this
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) GetUnit() string {
    if o == nil || utils.IsNil(o.Unit) {
        var ret string
        return ret
    }
    return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) GetUnitOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Unit) {
        return nil, false
    }
    return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) HasUnit() bool {
    if o != nil && !utils.IsNil(o.Unit) {
        return true
    }

    return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) SetUnit(v string) {
    o.Unit = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) GetValue() string {
    if o == nil || utils.IsNil(o.Value) {
        var ret string
        return ret
    }
    return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) GetValueOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Value) {
        return nil, false
    }
    return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) HasValue() bool {
    if o != nil && !utils.IsNil(o.Value) {
        return true
    }

    return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) SetValue(v string) {
    o.Value = &v
}

func (o Product202509PartialEditGlobalProductRequestBodyPackageWeight) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditGlobalProductRequestBodyPackageWeight) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Unit) {
        toSerialize["unit"] = o.Unit
    }
    if !utils.IsNil(o.Value) {
        toSerialize["value"] = o.Value
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditGlobalProductRequestBodyPackageWeight) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditGlobalProductRequestBodyPackageWeight := _Product202509PartialEditGlobalProductRequestBodyPackageWeight{}

    err = json.Unmarshal(data, &varProduct202509PartialEditGlobalProductRequestBodyPackageWeight)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditGlobalProductRequestBodyPackageWeight(varProduct202509PartialEditGlobalProductRequestBodyPackageWeight)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "unit")
        delete(additionalProperties, "value")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight struct {
	value *Product202509PartialEditGlobalProductRequestBodyPackageWeight
	isSet bool
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight) Get() *Product202509PartialEditGlobalProductRequestBodyPackageWeight {
	return v.value
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight) Set(val *Product202509PartialEditGlobalProductRequestBodyPackageWeight) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight(val *Product202509PartialEditGlobalProductRequestBodyPackageWeight) *NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight {
	return &NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyPackageWeight) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


