/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditProductRequestBodySkus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditProductRequestBodySkus{}

// Product202509PartialEditProductRequestBodySkus struct for Product202509PartialEditProductRequestBodySkus
type Product202509PartialEditProductRequestBodySkus struct {
    // The SKU list price (e.g. MSRP, RRP) or original price information on external ecommerce platforms. Applicable only for selected sellers in the US market.  **Note**: This value may appear as the strikethrough price on the product page. However, whether the strikethrough price is shown and the amount shown are subject to the audit team's review and decision based on various pricing information.
    ExternalListPrices []Product202509PartialEditProductRequestBodySkusExternalListPrices `json:"external_list_prices,omitempty"`
    // An external identifier used in an external ecommerce platform. This is used to associate the SKU between TikTok Shop and the external ecommerce platform.  Max length: 999 characters
    ExternalSkuId *string `json:"external_sku_id,omitempty"`
    // A comma-delimited list of URLs for third-party product listing pages where consumers can place orders. Add this property if you have products listed on third-party sites other than TikTok Shop and would like to map them. Max string length: 500
    ExternalUrls []string `json:"external_urls,omitempty"`
    // If the SKU belongs to a virtual bundle (containing multiple individual SKUs), you can add up to 10 additional identifier codes here for the SKUs included in the bundle.  **Format**: GTIN: 14 digits  EAN: 8, 13, or 14 digits  UPC: 12 digits  ISBN: 13 digits, or 9 digits ending in capital `X`  **Note**:  - Applicable only for the EU market.  - The identifier code must be unique for each SKU, with no repetition allowed.
    ExtraIdentifierCodes []string `json:"extra_identifier_codes,omitempty"`
    // The fees required for this product based on TikTok Shop policies. Fees are required only for certain product categories, retrieve the requirements from the [Get Category Rules API](https://partner.tiktokshop.com/docv2/page/6509c0febace3e02b74594a9). 
    Fees []Product202509PartialEditProductRequestBodySkusFees `json:"fees,omitempty"`
    // The SKU ID generated by TikTok Shop. One product can contain multiple SKU IDs.  **Note**:  - To edit an existing SKU, include its SKU ID. - Any existing SKU IDs not listed here will result in the deletion of those SKUs. For example, if this product contains 5 SKUs and you only provide 2 SKU IDs, the remaining 3 will be deleted. - To create new SKUs, leave the SKU ID blank and complete the other fields.
    Id *string `json:"id,omitempty"`
    IdentifierCode *Product202509PartialEditProductRequestBodySkusIdentifierCode `json:"identifier_code,omitempty"`
    // SKU inventory information. **Note**: If you are saving a post-live draft with `save_mode=AS_DRAFT`, this field is not supported and will not be saved. When using Get Product to retrieve the draft, the values will reflect those in the base version.
    Inventory []Product202509PartialEditProductRequestBodySkusInventory `json:"inventory,omitempty"`
    ListPrice *Product202509PartialEditProductRequestBodySkusListPrice `json:"list_price,omitempty"`
    PreSale *Product202509PartialEditProductRequestBodySkusPreSale `json:"pre_sale,omitempty"`
    Price *Product202509PartialEditProductRequestBodySkusPrice `json:"price,omitempty"`
    // A list of attributes  (e.g. size, color, length) that define each variant of a product.  **Note**:  - You must retain at least 1 sales attribute, deleting all existing sales attributes is not allowed. - You can only have up to 3 types of sales attributes per product. - Each SKU must include the same number and type of sales attributes. For example, you cannot have one SKU that has only a Color attribute, while another SKU has both Color and Size attributes. - Provide either a built-in ID or a custom name; if both are provided, the ID takes priority. - The `id/name` and `value_id/value_name` pairs must be unique in each SKU. For example, you cannot repeat `\"name\": \"Color\"`, `\"value_name\": \"Red\"` in different SKUs.
    SalesAttributes []Product202509PartialEditProductRequestBodySkusSalesAttributes `json:"sales_attributes,omitempty"`
    // An internal code/name for managing SKUs, not visible to buyers.   - Valid length: 1-50 characters - Format: Text without spaces
    SellerSku *string `json:"seller_sku,omitempty"`
    // The total quantity/volume of the product represented by the SKU. For example, if the SKU represents 500ml of water, this value would be 500 if the unit type is defined as ml. Valid range: [0.01, 99,999.9999]  Applicable only for the EU market.  **Note**:  - This is mainly used to calculate the unit price of the SKU, and is required only if you wish to display the unit price to facilitate easier price comparisons across different products and packaging sizes. - Unit price = Selling price/(SKU unit count/base unit count). Therefore if you want to obtain the unit price, you would also need to define the \"base unit count\" and the \"unit type\" product attributes. Retrieve the relevant information for these product attributes by using the [Get Attributes API](https://partner.tiktokshop.com/docv2/page/6509c5784a0bb702c0561cc8). The unit price would then be returned in the [Get Product API](https://partner.tiktokshop.com/docv2/page/6509d85b4a0bb702c057fdda).
    SkuUnitCount *string `json:"sku_unit_count,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditProductRequestBodySkus Product202509PartialEditProductRequestBodySkus

// NewProduct202509PartialEditProductRequestBodySkus instantiates a new Product202509PartialEditProductRequestBodySkus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditProductRequestBodySkus() *Product202509PartialEditProductRequestBodySkus {
    this := Product202509PartialEditProductRequestBodySkus{}
    return &this
}

// NewProduct202509PartialEditProductRequestBodySkusWithDefaults instantiates a new Product202509PartialEditProductRequestBodySkus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditProductRequestBodySkusWithDefaults() *Product202509PartialEditProductRequestBodySkus {
    this := Product202509PartialEditProductRequestBodySkus{}
    return &this
}

// GetExternalListPrices returns the ExternalListPrices field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetExternalListPrices() []Product202509PartialEditProductRequestBodySkusExternalListPrices {
    if o == nil || utils.IsNil(o.ExternalListPrices) {
        var ret []Product202509PartialEditProductRequestBodySkusExternalListPrices
        return ret
    }
    return o.ExternalListPrices
}

// GetExternalListPricesOk returns a tuple with the ExternalListPrices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetExternalListPricesOk() ([]Product202509PartialEditProductRequestBodySkusExternalListPrices, bool) {
    if o == nil || utils.IsNil(o.ExternalListPrices) {
        return nil, false
    }
    return o.ExternalListPrices, true
}

// HasExternalListPrices returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasExternalListPrices() bool {
    if o != nil && !utils.IsNil(o.ExternalListPrices) {
        return true
    }

    return false
}

// SetExternalListPrices gets a reference to the given []Product202509PartialEditProductRequestBodySkusExternalListPrices and assigns it to the ExternalListPrices field.
func (o *Product202509PartialEditProductRequestBodySkus) SetExternalListPrices(v []Product202509PartialEditProductRequestBodySkusExternalListPrices) {
    o.ExternalListPrices = v
}

// GetExternalSkuId returns the ExternalSkuId field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetExternalSkuId() string {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        var ret string
        return ret
    }
    return *o.ExternalSkuId
}

// GetExternalSkuIdOk returns a tuple with the ExternalSkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetExternalSkuIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        return nil, false
    }
    return o.ExternalSkuId, true
}

// HasExternalSkuId returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasExternalSkuId() bool {
    if o != nil && !utils.IsNil(o.ExternalSkuId) {
        return true
    }

    return false
}

// SetExternalSkuId gets a reference to the given string and assigns it to the ExternalSkuId field.
func (o *Product202509PartialEditProductRequestBodySkus) SetExternalSkuId(v string) {
    o.ExternalSkuId = &v
}

// GetExternalUrls returns the ExternalUrls field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetExternalUrls() []string {
    if o == nil || utils.IsNil(o.ExternalUrls) {
        var ret []string
        return ret
    }
    return o.ExternalUrls
}

// GetExternalUrlsOk returns a tuple with the ExternalUrls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetExternalUrlsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.ExternalUrls) {
        return nil, false
    }
    return o.ExternalUrls, true
}

// HasExternalUrls returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasExternalUrls() bool {
    if o != nil && !utils.IsNil(o.ExternalUrls) {
        return true
    }

    return false
}

// SetExternalUrls gets a reference to the given []string and assigns it to the ExternalUrls field.
func (o *Product202509PartialEditProductRequestBodySkus) SetExternalUrls(v []string) {
    o.ExternalUrls = v
}

// GetExtraIdentifierCodes returns the ExtraIdentifierCodes field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetExtraIdentifierCodes() []string {
    if o == nil || utils.IsNil(o.ExtraIdentifierCodes) {
        var ret []string
        return ret
    }
    return o.ExtraIdentifierCodes
}

// GetExtraIdentifierCodesOk returns a tuple with the ExtraIdentifierCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetExtraIdentifierCodesOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.ExtraIdentifierCodes) {
        return nil, false
    }
    return o.ExtraIdentifierCodes, true
}

// HasExtraIdentifierCodes returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasExtraIdentifierCodes() bool {
    if o != nil && !utils.IsNil(o.ExtraIdentifierCodes) {
        return true
    }

    return false
}

// SetExtraIdentifierCodes gets a reference to the given []string and assigns it to the ExtraIdentifierCodes field.
func (o *Product202509PartialEditProductRequestBodySkus) SetExtraIdentifierCodes(v []string) {
    o.ExtraIdentifierCodes = v
}

// GetFees returns the Fees field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetFees() []Product202509PartialEditProductRequestBodySkusFees {
    if o == nil || utils.IsNil(o.Fees) {
        var ret []Product202509PartialEditProductRequestBodySkusFees
        return ret
    }
    return o.Fees
}

// GetFeesOk returns a tuple with the Fees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetFeesOk() ([]Product202509PartialEditProductRequestBodySkusFees, bool) {
    if o == nil || utils.IsNil(o.Fees) {
        return nil, false
    }
    return o.Fees, true
}

// HasFees returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasFees() bool {
    if o != nil && !utils.IsNil(o.Fees) {
        return true
    }

    return false
}

// SetFees gets a reference to the given []Product202509PartialEditProductRequestBodySkusFees and assigns it to the Fees field.
func (o *Product202509PartialEditProductRequestBodySkus) SetFees(v []Product202509PartialEditProductRequestBodySkusFees) {
    o.Fees = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509PartialEditProductRequestBodySkus) SetId(v string) {
    o.Id = &v
}

// GetIdentifierCode returns the IdentifierCode field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetIdentifierCode() Product202509PartialEditProductRequestBodySkusIdentifierCode {
    if o == nil || utils.IsNil(o.IdentifierCode) {
        var ret Product202509PartialEditProductRequestBodySkusIdentifierCode
        return ret
    }
    return *o.IdentifierCode
}

// GetIdentifierCodeOk returns a tuple with the IdentifierCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetIdentifierCodeOk() (*Product202509PartialEditProductRequestBodySkusIdentifierCode, bool) {
    if o == nil || utils.IsNil(o.IdentifierCode) {
        return nil, false
    }
    return o.IdentifierCode, true
}

// HasIdentifierCode returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasIdentifierCode() bool {
    if o != nil && !utils.IsNil(o.IdentifierCode) {
        return true
    }

    return false
}

// SetIdentifierCode gets a reference to the given Product202509PartialEditProductRequestBodySkusIdentifierCode and assigns it to the IdentifierCode field.
func (o *Product202509PartialEditProductRequestBodySkus) SetIdentifierCode(v Product202509PartialEditProductRequestBodySkusIdentifierCode) {
    o.IdentifierCode = &v
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetInventory() []Product202509PartialEditProductRequestBodySkusInventory {
    if o == nil || utils.IsNil(o.Inventory) {
        var ret []Product202509PartialEditProductRequestBodySkusInventory
        return ret
    }
    return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetInventoryOk() ([]Product202509PartialEditProductRequestBodySkusInventory, bool) {
    if o == nil || utils.IsNil(o.Inventory) {
        return nil, false
    }
    return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasInventory() bool {
    if o != nil && !utils.IsNil(o.Inventory) {
        return true
    }

    return false
}

// SetInventory gets a reference to the given []Product202509PartialEditProductRequestBodySkusInventory and assigns it to the Inventory field.
func (o *Product202509PartialEditProductRequestBodySkus) SetInventory(v []Product202509PartialEditProductRequestBodySkusInventory) {
    o.Inventory = v
}

// GetListPrice returns the ListPrice field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetListPrice() Product202509PartialEditProductRequestBodySkusListPrice {
    if o == nil || utils.IsNil(o.ListPrice) {
        var ret Product202509PartialEditProductRequestBodySkusListPrice
        return ret
    }
    return *o.ListPrice
}

// GetListPriceOk returns a tuple with the ListPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetListPriceOk() (*Product202509PartialEditProductRequestBodySkusListPrice, bool) {
    if o == nil || utils.IsNil(o.ListPrice) {
        return nil, false
    }
    return o.ListPrice, true
}

// HasListPrice returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasListPrice() bool {
    if o != nil && !utils.IsNil(o.ListPrice) {
        return true
    }

    return false
}

// SetListPrice gets a reference to the given Product202509PartialEditProductRequestBodySkusListPrice and assigns it to the ListPrice field.
func (o *Product202509PartialEditProductRequestBodySkus) SetListPrice(v Product202509PartialEditProductRequestBodySkusListPrice) {
    o.ListPrice = &v
}

// GetPreSale returns the PreSale field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetPreSale() Product202509PartialEditProductRequestBodySkusPreSale {
    if o == nil || utils.IsNil(o.PreSale) {
        var ret Product202509PartialEditProductRequestBodySkusPreSale
        return ret
    }
    return *o.PreSale
}

// GetPreSaleOk returns a tuple with the PreSale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetPreSaleOk() (*Product202509PartialEditProductRequestBodySkusPreSale, bool) {
    if o == nil || utils.IsNil(o.PreSale) {
        return nil, false
    }
    return o.PreSale, true
}

// HasPreSale returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasPreSale() bool {
    if o != nil && !utils.IsNil(o.PreSale) {
        return true
    }

    return false
}

// SetPreSale gets a reference to the given Product202509PartialEditProductRequestBodySkusPreSale and assigns it to the PreSale field.
func (o *Product202509PartialEditProductRequestBodySkus) SetPreSale(v Product202509PartialEditProductRequestBodySkusPreSale) {
    o.PreSale = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetPrice() Product202509PartialEditProductRequestBodySkusPrice {
    if o == nil || utils.IsNil(o.Price) {
        var ret Product202509PartialEditProductRequestBodySkusPrice
        return ret
    }
    return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetPriceOk() (*Product202509PartialEditProductRequestBodySkusPrice, bool) {
    if o == nil || utils.IsNil(o.Price) {
        return nil, false
    }
    return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasPrice() bool {
    if o != nil && !utils.IsNil(o.Price) {
        return true
    }

    return false
}

// SetPrice gets a reference to the given Product202509PartialEditProductRequestBodySkusPrice and assigns it to the Price field.
func (o *Product202509PartialEditProductRequestBodySkus) SetPrice(v Product202509PartialEditProductRequestBodySkusPrice) {
    o.Price = &v
}

// GetSalesAttributes returns the SalesAttributes field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetSalesAttributes() []Product202509PartialEditProductRequestBodySkusSalesAttributes {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        var ret []Product202509PartialEditProductRequestBodySkusSalesAttributes
        return ret
    }
    return o.SalesAttributes
}

// GetSalesAttributesOk returns a tuple with the SalesAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetSalesAttributesOk() ([]Product202509PartialEditProductRequestBodySkusSalesAttributes, bool) {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        return nil, false
    }
    return o.SalesAttributes, true
}

// HasSalesAttributes returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasSalesAttributes() bool {
    if o != nil && !utils.IsNil(o.SalesAttributes) {
        return true
    }

    return false
}

// SetSalesAttributes gets a reference to the given []Product202509PartialEditProductRequestBodySkusSalesAttributes and assigns it to the SalesAttributes field.
func (o *Product202509PartialEditProductRequestBodySkus) SetSalesAttributes(v []Product202509PartialEditProductRequestBodySkusSalesAttributes) {
    o.SalesAttributes = v
}

// GetSellerSku returns the SellerSku field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetSellerSku() string {
    if o == nil || utils.IsNil(o.SellerSku) {
        var ret string
        return ret
    }
    return *o.SellerSku
}

// GetSellerSkuOk returns a tuple with the SellerSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetSellerSkuOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerSku) {
        return nil, false
    }
    return o.SellerSku, true
}

// HasSellerSku returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasSellerSku() bool {
    if o != nil && !utils.IsNil(o.SellerSku) {
        return true
    }

    return false
}

// SetSellerSku gets a reference to the given string and assigns it to the SellerSku field.
func (o *Product202509PartialEditProductRequestBodySkus) SetSellerSku(v string) {
    o.SellerSku = &v
}

// GetSkuUnitCount returns the SkuUnitCount field value if set, zero value otherwise.
func (o *Product202509PartialEditProductRequestBodySkus) GetSkuUnitCount() string {
    if o == nil || utils.IsNil(o.SkuUnitCount) {
        var ret string
        return ret
    }
    return *o.SkuUnitCount
}

// GetSkuUnitCountOk returns a tuple with the SkuUnitCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductRequestBodySkus) GetSkuUnitCountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SkuUnitCount) {
        return nil, false
    }
    return o.SkuUnitCount, true
}

// HasSkuUnitCount returns a boolean if a field has been set.
func (o *Product202509PartialEditProductRequestBodySkus) HasSkuUnitCount() bool {
    if o != nil && !utils.IsNil(o.SkuUnitCount) {
        return true
    }

    return false
}

// SetSkuUnitCount gets a reference to the given string and assigns it to the SkuUnitCount field.
func (o *Product202509PartialEditProductRequestBodySkus) SetSkuUnitCount(v string) {
    o.SkuUnitCount = &v
}

func (o Product202509PartialEditProductRequestBodySkus) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditProductRequestBodySkus) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ExternalListPrices) {
        toSerialize["external_list_prices"] = o.ExternalListPrices
    }
    if !utils.IsNil(o.ExternalSkuId) {
        toSerialize["external_sku_id"] = o.ExternalSkuId
    }
    if !utils.IsNil(o.ExternalUrls) {
        toSerialize["external_urls"] = o.ExternalUrls
    }
    if !utils.IsNil(o.ExtraIdentifierCodes) {
        toSerialize["extra_identifier_codes"] = o.ExtraIdentifierCodes
    }
    if !utils.IsNil(o.Fees) {
        toSerialize["fees"] = o.Fees
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.IdentifierCode) {
        toSerialize["identifier_code"] = o.IdentifierCode
    }
    if !utils.IsNil(o.Inventory) {
        toSerialize["inventory"] = o.Inventory
    }
    if !utils.IsNil(o.ListPrice) {
        toSerialize["list_price"] = o.ListPrice
    }
    if !utils.IsNil(o.PreSale) {
        toSerialize["pre_sale"] = o.PreSale
    }
    if !utils.IsNil(o.Price) {
        toSerialize["price"] = o.Price
    }
    if !utils.IsNil(o.SalesAttributes) {
        toSerialize["sales_attributes"] = o.SalesAttributes
    }
    if !utils.IsNil(o.SellerSku) {
        toSerialize["seller_sku"] = o.SellerSku
    }
    if !utils.IsNil(o.SkuUnitCount) {
        toSerialize["sku_unit_count"] = o.SkuUnitCount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditProductRequestBodySkus) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditProductRequestBodySkus := _Product202509PartialEditProductRequestBodySkus{}

    err = json.Unmarshal(data, &varProduct202509PartialEditProductRequestBodySkus)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditProductRequestBodySkus(varProduct202509PartialEditProductRequestBodySkus)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "external_list_prices")
        delete(additionalProperties, "external_sku_id")
        delete(additionalProperties, "external_urls")
        delete(additionalProperties, "extra_identifier_codes")
        delete(additionalProperties, "fees")
        delete(additionalProperties, "id")
        delete(additionalProperties, "identifier_code")
        delete(additionalProperties, "inventory")
        delete(additionalProperties, "list_price")
        delete(additionalProperties, "pre_sale")
        delete(additionalProperties, "price")
        delete(additionalProperties, "sales_attributes")
        delete(additionalProperties, "seller_sku")
        delete(additionalProperties, "sku_unit_count")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditProductRequestBodySkus struct {
	value *Product202509PartialEditProductRequestBodySkus
	isSet bool
}

func (v NullableProduct202509PartialEditProductRequestBodySkus) Get() *Product202509PartialEditProductRequestBodySkus {
	return v.value
}

func (v *NullableProduct202509PartialEditProductRequestBodySkus) Set(val *Product202509PartialEditProductRequestBodySkus) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditProductRequestBodySkus) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditProductRequestBodySkus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditProductRequestBodySkus(val *Product202509PartialEditProductRequestBodySkus) *NullableProduct202509PartialEditProductRequestBodySkus {
	return &NullableProduct202509PartialEditProductRequestBodySkus{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditProductRequestBodySkus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditProductRequestBodySkus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


