/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditGlobalProductRequestBodyVideo type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditGlobalProductRequestBodyVideo{}

// Product202509PartialEditGlobalProductRequestBodyVideo struct for Product202509PartialEditGlobalProductRequestBodyVideo
type Product202509PartialEditGlobalProductRequestBodyVideo struct {
    // The ID of the product video. Use the [Upload Product File API](https://partner.tiktokshop.com/docv2/page/6509dffdc16ffe02b8dc10c5) to upload the video first and obtain the corresponding file ID.
    Id *string `json:"id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditGlobalProductRequestBodyVideo Product202509PartialEditGlobalProductRequestBodyVideo

// NewProduct202509PartialEditGlobalProductRequestBodyVideo instantiates a new Product202509PartialEditGlobalProductRequestBodyVideo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditGlobalProductRequestBodyVideo() *Product202509PartialEditGlobalProductRequestBodyVideo {
    this := Product202509PartialEditGlobalProductRequestBodyVideo{}
    return &this
}

// NewProduct202509PartialEditGlobalProductRequestBodyVideoWithDefaults instantiates a new Product202509PartialEditGlobalProductRequestBodyVideo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditGlobalProductRequestBodyVideoWithDefaults() *Product202509PartialEditGlobalProductRequestBodyVideo {
    this := Product202509PartialEditGlobalProductRequestBodyVideo{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyVideo) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyVideo) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyVideo) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509PartialEditGlobalProductRequestBodyVideo) SetId(v string) {
    o.Id = &v
}

func (o Product202509PartialEditGlobalProductRequestBodyVideo) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditGlobalProductRequestBodyVideo) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditGlobalProductRequestBodyVideo) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditGlobalProductRequestBodyVideo := _Product202509PartialEditGlobalProductRequestBodyVideo{}

    err = json.Unmarshal(data, &varProduct202509PartialEditGlobalProductRequestBodyVideo)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditGlobalProductRequestBodyVideo(varProduct202509PartialEditGlobalProductRequestBodyVideo)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditGlobalProductRequestBodyVideo struct {
	value *Product202509PartialEditGlobalProductRequestBodyVideo
	isSet bool
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyVideo) Get() *Product202509PartialEditGlobalProductRequestBodyVideo {
	return v.value
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyVideo) Set(val *Product202509PartialEditGlobalProductRequestBodyVideo) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyVideo) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyVideo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditGlobalProductRequestBodyVideo(val *Product202509PartialEditGlobalProductRequestBodyVideo) *NullableProduct202509PartialEditGlobalProductRequestBodyVideo {
	return &NullableProduct202509PartialEditGlobalProductRequestBodyVideo{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyVideo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyVideo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


