/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditGlobalProductRequestBodyManufacturer type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditGlobalProductRequestBodyManufacturer{}

// Product202509PartialEditGlobalProductRequestBodyManufacturer struct for Product202509PartialEditGlobalProductRequestBodyManufacturer
type Product202509PartialEditGlobalProductRequestBodyManufacturer struct {
    // The address of the manufacturer.
    Address *string `json:"address,omitempty"`
    // The email address of the manufacturer.
    Email *string `json:"email,omitempty"`
    // The name of the manufacturer.
    Name *string `json:"name,omitempty"`
    // The phone number of the manufacturer, prefixed by a plus `+` symbol.  There must be a space or hyphen between the country code and the local phone number.
    PhoneNumber *string `json:"phone_number,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditGlobalProductRequestBodyManufacturer Product202509PartialEditGlobalProductRequestBodyManufacturer

// NewProduct202509PartialEditGlobalProductRequestBodyManufacturer instantiates a new Product202509PartialEditGlobalProductRequestBodyManufacturer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditGlobalProductRequestBodyManufacturer() *Product202509PartialEditGlobalProductRequestBodyManufacturer {
    this := Product202509PartialEditGlobalProductRequestBodyManufacturer{}
    return &this
}

// NewProduct202509PartialEditGlobalProductRequestBodyManufacturerWithDefaults instantiates a new Product202509PartialEditGlobalProductRequestBodyManufacturer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditGlobalProductRequestBodyManufacturerWithDefaults() *Product202509PartialEditGlobalProductRequestBodyManufacturer {
    this := Product202509PartialEditGlobalProductRequestBodyManufacturer{}
    return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetAddress() string {
    if o == nil || utils.IsNil(o.Address) {
        var ret string
        return ret
    }
    return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetAddressOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Address) {
        return nil, false
    }
    return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) HasAddress() bool {
    if o != nil && !utils.IsNil(o.Address) {
        return true
    }

    return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) SetAddress(v string) {
    o.Address = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetEmail() string {
    if o == nil || utils.IsNil(o.Email) {
        var ret string
        return ret
    }
    return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetEmailOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Email) {
        return nil, false
    }
    return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) HasEmail() bool {
    if o != nil && !utils.IsNil(o.Email) {
        return true
    }

    return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) SetEmail(v string) {
    o.Email = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetName() string {
    if o == nil || utils.IsNil(o.Name) {
        var ret string
        return ret
    }
    return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Name) {
        return nil, false
    }
    return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) HasName() bool {
    if o != nil && !utils.IsNil(o.Name) {
        return true
    }

    return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) SetName(v string) {
    o.Name = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetPhoneNumber() string {
    if o == nil || utils.IsNil(o.PhoneNumber) {
        var ret string
        return ret
    }
    return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) GetPhoneNumberOk() (*string, bool) {
    if o == nil || utils.IsNil(o.PhoneNumber) {
        return nil, false
    }
    return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) HasPhoneNumber() bool {
    if o != nil && !utils.IsNil(o.PhoneNumber) {
        return true
    }

    return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) SetPhoneNumber(v string) {
    o.PhoneNumber = &v
}

func (o Product202509PartialEditGlobalProductRequestBodyManufacturer) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditGlobalProductRequestBodyManufacturer) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Address) {
        toSerialize["address"] = o.Address
    }
    if !utils.IsNil(o.Email) {
        toSerialize["email"] = o.Email
    }
    if !utils.IsNil(o.Name) {
        toSerialize["name"] = o.Name
    }
    if !utils.IsNil(o.PhoneNumber) {
        toSerialize["phone_number"] = o.PhoneNumber
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditGlobalProductRequestBodyManufacturer) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditGlobalProductRequestBodyManufacturer := _Product202509PartialEditGlobalProductRequestBodyManufacturer{}

    err = json.Unmarshal(data, &varProduct202509PartialEditGlobalProductRequestBodyManufacturer)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditGlobalProductRequestBodyManufacturer(varProduct202509PartialEditGlobalProductRequestBodyManufacturer)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "address")
        delete(additionalProperties, "email")
        delete(additionalProperties, "name")
        delete(additionalProperties, "phone_number")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer struct {
	value *Product202509PartialEditGlobalProductRequestBodyManufacturer
	isSet bool
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer) Get() *Product202509PartialEditGlobalProductRequestBodyManufacturer {
	return v.value
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer) Set(val *Product202509PartialEditGlobalProductRequestBodyManufacturer) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditGlobalProductRequestBodyManufacturer(val *Product202509PartialEditGlobalProductRequestBodyManufacturer) *NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer {
	return &NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyManufacturer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


