/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditGlobalProductResponseDataGlobalSkus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditGlobalProductResponseDataGlobalSkus{}

// Product202509PartialEditGlobalProductResponseDataGlobalSkus struct for Product202509PartialEditGlobalProductResponseDataGlobalSkus
type Product202509PartialEditGlobalProductResponseDataGlobalSkus struct {
    // An external identifier used in an external ecommerce platform. This is used to associate the global SKU between TikTok Shop and the external ecommerce platform.  Max length: 999 characters
    ExternalGlobalSkuId *string `json:"external_global_sku_id,omitempty"`
    // The global SKU ID generated by TikTok Shop. One product can contain multiple SKU IDs.
    Id *string `json:"id,omitempty"`
    // A list of attributes  (e.g. size, color, length) that define each variant of a product.
    SalesAttributes []Product202509PartialEditGlobalProductResponseDataGlobalSkusSalesAttributes `json:"sales_attributes,omitempty"`
    // An internal code/name for managing SKUs, not visible to buyers.
    SellerSku *string `json:"seller_sku,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditGlobalProductResponseDataGlobalSkus Product202509PartialEditGlobalProductResponseDataGlobalSkus

// NewProduct202509PartialEditGlobalProductResponseDataGlobalSkus instantiates a new Product202509PartialEditGlobalProductResponseDataGlobalSkus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditGlobalProductResponseDataGlobalSkus() *Product202509PartialEditGlobalProductResponseDataGlobalSkus {
    this := Product202509PartialEditGlobalProductResponseDataGlobalSkus{}
    return &this
}

// NewProduct202509PartialEditGlobalProductResponseDataGlobalSkusWithDefaults instantiates a new Product202509PartialEditGlobalProductResponseDataGlobalSkus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditGlobalProductResponseDataGlobalSkusWithDefaults() *Product202509PartialEditGlobalProductResponseDataGlobalSkus {
    this := Product202509PartialEditGlobalProductResponseDataGlobalSkus{}
    return &this
}

// GetExternalGlobalSkuId returns the ExternalGlobalSkuId field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetExternalGlobalSkuId() string {
    if o == nil || utils.IsNil(o.ExternalGlobalSkuId) {
        var ret string
        return ret
    }
    return *o.ExternalGlobalSkuId
}

// GetExternalGlobalSkuIdOk returns a tuple with the ExternalGlobalSkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetExternalGlobalSkuIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ExternalGlobalSkuId) {
        return nil, false
    }
    return o.ExternalGlobalSkuId, true
}

// HasExternalGlobalSkuId returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) HasExternalGlobalSkuId() bool {
    if o != nil && !utils.IsNil(o.ExternalGlobalSkuId) {
        return true
    }

    return false
}

// SetExternalGlobalSkuId gets a reference to the given string and assigns it to the ExternalGlobalSkuId field.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) SetExternalGlobalSkuId(v string) {
    o.ExternalGlobalSkuId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) SetId(v string) {
    o.Id = &v
}

// GetSalesAttributes returns the SalesAttributes field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetSalesAttributes() []Product202509PartialEditGlobalProductResponseDataGlobalSkusSalesAttributes {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        var ret []Product202509PartialEditGlobalProductResponseDataGlobalSkusSalesAttributes
        return ret
    }
    return o.SalesAttributes
}

// GetSalesAttributesOk returns a tuple with the SalesAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetSalesAttributesOk() ([]Product202509PartialEditGlobalProductResponseDataGlobalSkusSalesAttributes, bool) {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        return nil, false
    }
    return o.SalesAttributes, true
}

// HasSalesAttributes returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) HasSalesAttributes() bool {
    if o != nil && !utils.IsNil(o.SalesAttributes) {
        return true
    }

    return false
}

// SetSalesAttributes gets a reference to the given []Product202509PartialEditGlobalProductResponseDataGlobalSkusSalesAttributes and assigns it to the SalesAttributes field.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) SetSalesAttributes(v []Product202509PartialEditGlobalProductResponseDataGlobalSkusSalesAttributes) {
    o.SalesAttributes = v
}

// GetSellerSku returns the SellerSku field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetSellerSku() string {
    if o == nil || utils.IsNil(o.SellerSku) {
        var ret string
        return ret
    }
    return *o.SellerSku
}

// GetSellerSkuOk returns a tuple with the SellerSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) GetSellerSkuOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerSku) {
        return nil, false
    }
    return o.SellerSku, true
}

// HasSellerSku returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) HasSellerSku() bool {
    if o != nil && !utils.IsNil(o.SellerSku) {
        return true
    }

    return false
}

// SetSellerSku gets a reference to the given string and assigns it to the SellerSku field.
func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) SetSellerSku(v string) {
    o.SellerSku = &v
}

func (o Product202509PartialEditGlobalProductResponseDataGlobalSkus) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditGlobalProductResponseDataGlobalSkus) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ExternalGlobalSkuId) {
        toSerialize["external_global_sku_id"] = o.ExternalGlobalSkuId
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.SalesAttributes) {
        toSerialize["sales_attributes"] = o.SalesAttributes
    }
    if !utils.IsNil(o.SellerSku) {
        toSerialize["seller_sku"] = o.SellerSku
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditGlobalProductResponseDataGlobalSkus) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditGlobalProductResponseDataGlobalSkus := _Product202509PartialEditGlobalProductResponseDataGlobalSkus{}

    err = json.Unmarshal(data, &varProduct202509PartialEditGlobalProductResponseDataGlobalSkus)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditGlobalProductResponseDataGlobalSkus(varProduct202509PartialEditGlobalProductResponseDataGlobalSkus)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "external_global_sku_id")
        delete(additionalProperties, "id")
        delete(additionalProperties, "sales_attributes")
        delete(additionalProperties, "seller_sku")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus struct {
	value *Product202509PartialEditGlobalProductResponseDataGlobalSkus
	isSet bool
}

func (v NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus) Get() *Product202509PartialEditGlobalProductResponseDataGlobalSkus {
	return v.value
}

func (v *NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus) Set(val *Product202509PartialEditGlobalProductResponseDataGlobalSkus) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus(val *Product202509PartialEditGlobalProductResponseDataGlobalSkus) *NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus {
	return &NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditGlobalProductResponseDataGlobalSkus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


