/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditProductResponseDataSkusSalesAttributes type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditProductResponseDataSkusSalesAttributes{}

// Product202509PartialEditProductResponseDataSkusSalesAttributes struct for Product202509PartialEditProductResponseDataSkusSalesAttributes
type Product202509PartialEditProductResponseDataSkusSalesAttributes struct {
    // The sales attribute ID.  If you included the custom sales attribute name in the request, this is a newly generated ID.
    Id *string `json:"id,omitempty"`
    // The sales attribute value ID.  If you included the custom sales attribute value name in the request, this is a newly generated ID.
    ValueId *string `json:"value_id,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditProductResponseDataSkusSalesAttributes Product202509PartialEditProductResponseDataSkusSalesAttributes

// NewProduct202509PartialEditProductResponseDataSkusSalesAttributes instantiates a new Product202509PartialEditProductResponseDataSkusSalesAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditProductResponseDataSkusSalesAttributes() *Product202509PartialEditProductResponseDataSkusSalesAttributes {
    this := Product202509PartialEditProductResponseDataSkusSalesAttributes{}
    return &this
}

// NewProduct202509PartialEditProductResponseDataSkusSalesAttributesWithDefaults instantiates a new Product202509PartialEditProductResponseDataSkusSalesAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditProductResponseDataSkusSalesAttributesWithDefaults() *Product202509PartialEditProductResponseDataSkusSalesAttributes {
    this := Product202509PartialEditProductResponseDataSkusSalesAttributes{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) SetId(v string) {
    o.Id = &v
}

// GetValueId returns the ValueId field value if set, zero value otherwise.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) GetValueId() string {
    if o == nil || utils.IsNil(o.ValueId) {
        var ret string
        return ret
    }
    return *o.ValueId
}

// GetValueIdOk returns a tuple with the ValueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) GetValueIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ValueId) {
        return nil, false
    }
    return o.ValueId, true
}

// HasValueId returns a boolean if a field has been set.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) HasValueId() bool {
    if o != nil && !utils.IsNil(o.ValueId) {
        return true
    }

    return false
}

// SetValueId gets a reference to the given string and assigns it to the ValueId field.
func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) SetValueId(v string) {
    o.ValueId = &v
}

func (o Product202509PartialEditProductResponseDataSkusSalesAttributes) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditProductResponseDataSkusSalesAttributes) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.ValueId) {
        toSerialize["value_id"] = o.ValueId
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditProductResponseDataSkusSalesAttributes) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditProductResponseDataSkusSalesAttributes := _Product202509PartialEditProductResponseDataSkusSalesAttributes{}

    err = json.Unmarshal(data, &varProduct202509PartialEditProductResponseDataSkusSalesAttributes)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditProductResponseDataSkusSalesAttributes(varProduct202509PartialEditProductResponseDataSkusSalesAttributes)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "id")
        delete(additionalProperties, "value_id")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes struct {
	value *Product202509PartialEditProductResponseDataSkusSalesAttributes
	isSet bool
}

func (v NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes) Get() *Product202509PartialEditProductResponseDataSkusSalesAttributes {
	return v.value
}

func (v *NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes) Set(val *Product202509PartialEditProductResponseDataSkusSalesAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditProductResponseDataSkusSalesAttributes(val *Product202509PartialEditProductResponseDataSkusSalesAttributes) *NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes {
	return &NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditProductResponseDataSkusSalesAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


