/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202509

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202509PartialEditGlobalProductRequestBodyProductAttributes type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202509PartialEditGlobalProductRequestBodyProductAttributes{}

// Product202509PartialEditGlobalProductRequestBodyProductAttributes struct for Product202509PartialEditGlobalProductRequestBodyProductAttributes
type Product202509PartialEditGlobalProductRequestBodyProductAttributes struct {
    // The ID of the product attribute, retrieved from the [Get Global Attributes API](https://partner.tiktokshop.com/docv2/page/650a0483c16ffe02b8dfc80a).
    Id *string `json:"id,omitempty"`
    // A list of selectable values for the product attribute. Max count: 300 for US; 100 for other regions.  **Note**: Provide either a built-in ID or a custom name; if both are provided, the ID takes priority.
    Values []Product202509PartialEditGlobalProductRequestBodyProductAttributesValues `json:"values,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202509PartialEditGlobalProductRequestBodyProductAttributes Product202509PartialEditGlobalProductRequestBodyProductAttributes

// NewProduct202509PartialEditGlobalProductRequestBodyProductAttributes instantiates a new Product202509PartialEditGlobalProductRequestBodyProductAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202509PartialEditGlobalProductRequestBodyProductAttributes() *Product202509PartialEditGlobalProductRequestBodyProductAttributes {
    this := Product202509PartialEditGlobalProductRequestBodyProductAttributes{}
    return &this
}

// NewProduct202509PartialEditGlobalProductRequestBodyProductAttributesWithDefaults instantiates a new Product202509PartialEditGlobalProductRequestBodyProductAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202509PartialEditGlobalProductRequestBodyProductAttributesWithDefaults() *Product202509PartialEditGlobalProductRequestBodyProductAttributes {
    this := Product202509PartialEditGlobalProductRequestBodyProductAttributes{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) SetId(v string) {
    o.Id = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) GetValues() []Product202509PartialEditGlobalProductRequestBodyProductAttributesValues {
    if o == nil || utils.IsNil(o.Values) {
        var ret []Product202509PartialEditGlobalProductRequestBodyProductAttributesValues
        return ret
    }
    return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) GetValuesOk() ([]Product202509PartialEditGlobalProductRequestBodyProductAttributesValues, bool) {
    if o == nil || utils.IsNil(o.Values) {
        return nil, false
    }
    return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) HasValues() bool {
    if o != nil && !utils.IsNil(o.Values) {
        return true
    }

    return false
}

// SetValues gets a reference to the given []Product202509PartialEditGlobalProductRequestBodyProductAttributesValues and assigns it to the Values field.
func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) SetValues(v []Product202509PartialEditGlobalProductRequestBodyProductAttributesValues) {
    o.Values = v
}

func (o Product202509PartialEditGlobalProductRequestBodyProductAttributes) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202509PartialEditGlobalProductRequestBodyProductAttributes) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Values) {
        toSerialize["values"] = o.Values
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202509PartialEditGlobalProductRequestBodyProductAttributes) UnmarshalJSON(data []byte) (err error) {
    varProduct202509PartialEditGlobalProductRequestBodyProductAttributes := _Product202509PartialEditGlobalProductRequestBodyProductAttributes{}

    err = json.Unmarshal(data, &varProduct202509PartialEditGlobalProductRequestBodyProductAttributes)

    if err != nil {
        return err
    }

    *o = Product202509PartialEditGlobalProductRequestBodyProductAttributes(varProduct202509PartialEditGlobalProductRequestBodyProductAttributes)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "id")
        delete(additionalProperties, "values")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes struct {
	value *Product202509PartialEditGlobalProductRequestBodyProductAttributes
	isSet bool
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes) Get() *Product202509PartialEditGlobalProductRequestBodyProductAttributes {
	return v.value
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes) Set(val *Product202509PartialEditGlobalProductRequestBodyProductAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes(val *Product202509PartialEditGlobalProductRequestBodyProductAttributes) *NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes {
	return &NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes{value: val, isSet: true}
}

func (v NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202509PartialEditGlobalProductRequestBodyProductAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


