/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finance_v202501

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent{}

// Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent struct for Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent
type Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent struct {
    // The shipping fee borne by the customer.This is part of `customer_paid_shipping_fee_amount`.
    CustomerShippingFee *string `json:"customer_shipping_fee,omitempty"`
    // The fee to offset TikTok Shop Shipping Incentive or customer-paid shipping fee, resulting in a net charge of $0 to the seller.  Applicable only for the US.
    CustomerShippingFeeOffsetAmount *string `json:"customer_shipping_fee_offset_amount,omitempty"`
    // The shipping fee incurred by the seller for using TikTok Shipping. This is part of `actual_shipping_fee_amount`.
    FbmShippingCostAmount *string `json:"fbm_shipping_cost_amount,omitempty"`
    // The shipping and warehouse fulfillment fee incurred by the seller for orders fulfilled by TikTok (FBT). This is part of `actual_shipping_fee_amount`.  Applicable only for the US.
    FbtFulfillmentFeeAmount *string `json:"fbt_fulfillment_fee_amount,omitempty"`
    // (**Deprecated**: This field is deprecated and will return an empty string. Please refer to `shipping_cost_breakdown.fbt_fulfillment_fee_reimbursement_amount` instead for the relevant details.)
    FbtFulfillmentFeeReimbursementAmount *string `json:"fbt_fulfillment_fee_reimbursement_amount,omitempty"`
    // The shipping fee incurred by the seller for orders fulfilled by TikTok (FBT). This is part of `actual_shipping_fee_amount`.  Applicable only for EU and UK.
    FbtShippingCostAmount *string `json:"fbt_shipping_cost_amount,omitempty"`
    // The shipping fee discount provided in accordance with a campaign policy. This is part of `shipping_fee_discount_amount`.
    PlatformShippingFeeDiscountAmount *string `json:"platform_shipping_fee_discount_amount,omitempty"`
    // The additional shipping incentive that the seller will receive if the seller signed up for the Co-Funded Free Shipping Program. A negative amount indicates a reversal of incentives due to order refunds attributed to the seller's responsibility. This is part of `shipping_fee_discount_amount`.
    PromoShippingIncentiveAmount *string `json:"promo_shipping_incentive_amount,omitempty"`
    // Refund the shipping fee borne by the customer. Include subsidies.This is part of `customer_paid_shipping_fee_amount`.
    RefundCustomerShippingFee *string `json:"refund_customer_shipping_fee,omitempty"`
    // Shipping fee returned to customers due returns and refunds.Does not include subsidies.This is part of `customer_paid_shipping_fee_amount`.
    RefundedCustomerShippingFeeAmount *string `json:"refunded_customer_shipping_fee_amount,omitempty"`
    // For shipping fee from returns and refunds, you pay up to a standard rate, and TikTok Shop covers the remaining amount.This is part of `customer_paid_shipping_fee_amount`.
    ReturnRefundSubsidyAmount *string `json:"return_refund_subsidy_amount,omitempty"`
    // The shipping fee discount provided by sellers.
    SellerShippingFeeDiscountAmount *string `json:"seller_shipping_fee_discount_amount,omitempty"`
    // The shipping fee subsidy funded by the platform for seller shipping. This is part of `shipping_fee_discount_amount`. - Positive amount represents a subsidy received by the seller. - Negative amount represents a subsidy that the seller must return to TikTok Shop.
    ShippingFeeSubsidyAmount *string `json:"shipping_fee_subsidy_amount,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent

// NewFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent instantiates a new Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent() *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent {
    this := Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent{}
    return &this
}

// NewFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponentWithDefaults instantiates a new Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponentWithDefaults() *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent {
    this := Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent{}
    return &this
}

// GetCustomerShippingFee returns the CustomerShippingFee field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetCustomerShippingFee() string {
    if o == nil || utils.IsNil(o.CustomerShippingFee) {
        var ret string
        return ret
    }
    return *o.CustomerShippingFee
}

// GetCustomerShippingFeeOk returns a tuple with the CustomerShippingFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetCustomerShippingFeeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CustomerShippingFee) {
        return nil, false
    }
    return o.CustomerShippingFee, true
}

// HasCustomerShippingFee returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasCustomerShippingFee() bool {
    if o != nil && !utils.IsNil(o.CustomerShippingFee) {
        return true
    }

    return false
}

// SetCustomerShippingFee gets a reference to the given string and assigns it to the CustomerShippingFee field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetCustomerShippingFee(v string) {
    o.CustomerShippingFee = &v
}

// GetCustomerShippingFeeOffsetAmount returns the CustomerShippingFeeOffsetAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetCustomerShippingFeeOffsetAmount() string {
    if o == nil || utils.IsNil(o.CustomerShippingFeeOffsetAmount) {
        var ret string
        return ret
    }
    return *o.CustomerShippingFeeOffsetAmount
}

// GetCustomerShippingFeeOffsetAmountOk returns a tuple with the CustomerShippingFeeOffsetAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetCustomerShippingFeeOffsetAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CustomerShippingFeeOffsetAmount) {
        return nil, false
    }
    return o.CustomerShippingFeeOffsetAmount, true
}

// HasCustomerShippingFeeOffsetAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasCustomerShippingFeeOffsetAmount() bool {
    if o != nil && !utils.IsNil(o.CustomerShippingFeeOffsetAmount) {
        return true
    }

    return false
}

// SetCustomerShippingFeeOffsetAmount gets a reference to the given string and assigns it to the CustomerShippingFeeOffsetAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetCustomerShippingFeeOffsetAmount(v string) {
    o.CustomerShippingFeeOffsetAmount = &v
}

// GetFbmShippingCostAmount returns the FbmShippingCostAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbmShippingCostAmount() string {
    if o == nil || utils.IsNil(o.FbmShippingCostAmount) {
        var ret string
        return ret
    }
    return *o.FbmShippingCostAmount
}

// GetFbmShippingCostAmountOk returns a tuple with the FbmShippingCostAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbmShippingCostAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.FbmShippingCostAmount) {
        return nil, false
    }
    return o.FbmShippingCostAmount, true
}

// HasFbmShippingCostAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasFbmShippingCostAmount() bool {
    if o != nil && !utils.IsNil(o.FbmShippingCostAmount) {
        return true
    }

    return false
}

// SetFbmShippingCostAmount gets a reference to the given string and assigns it to the FbmShippingCostAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetFbmShippingCostAmount(v string) {
    o.FbmShippingCostAmount = &v
}

// GetFbtFulfillmentFeeAmount returns the FbtFulfillmentFeeAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbtFulfillmentFeeAmount() string {
    if o == nil || utils.IsNil(o.FbtFulfillmentFeeAmount) {
        var ret string
        return ret
    }
    return *o.FbtFulfillmentFeeAmount
}

// GetFbtFulfillmentFeeAmountOk returns a tuple with the FbtFulfillmentFeeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbtFulfillmentFeeAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.FbtFulfillmentFeeAmount) {
        return nil, false
    }
    return o.FbtFulfillmentFeeAmount, true
}

// HasFbtFulfillmentFeeAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasFbtFulfillmentFeeAmount() bool {
    if o != nil && !utils.IsNil(o.FbtFulfillmentFeeAmount) {
        return true
    }

    return false
}

// SetFbtFulfillmentFeeAmount gets a reference to the given string and assigns it to the FbtFulfillmentFeeAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetFbtFulfillmentFeeAmount(v string) {
    o.FbtFulfillmentFeeAmount = &v
}

// GetFbtFulfillmentFeeReimbursementAmount returns the FbtFulfillmentFeeReimbursementAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbtFulfillmentFeeReimbursementAmount() string {
    if o == nil || utils.IsNil(o.FbtFulfillmentFeeReimbursementAmount) {
        var ret string
        return ret
    }
    return *o.FbtFulfillmentFeeReimbursementAmount
}

// GetFbtFulfillmentFeeReimbursementAmountOk returns a tuple with the FbtFulfillmentFeeReimbursementAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbtFulfillmentFeeReimbursementAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.FbtFulfillmentFeeReimbursementAmount) {
        return nil, false
    }
    return o.FbtFulfillmentFeeReimbursementAmount, true
}

// HasFbtFulfillmentFeeReimbursementAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasFbtFulfillmentFeeReimbursementAmount() bool {
    if o != nil && !utils.IsNil(o.FbtFulfillmentFeeReimbursementAmount) {
        return true
    }

    return false
}

// SetFbtFulfillmentFeeReimbursementAmount gets a reference to the given string and assigns it to the FbtFulfillmentFeeReimbursementAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetFbtFulfillmentFeeReimbursementAmount(v string) {
    o.FbtFulfillmentFeeReimbursementAmount = &v
}

// GetFbtShippingCostAmount returns the FbtShippingCostAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbtShippingCostAmount() string {
    if o == nil || utils.IsNil(o.FbtShippingCostAmount) {
        var ret string
        return ret
    }
    return *o.FbtShippingCostAmount
}

// GetFbtShippingCostAmountOk returns a tuple with the FbtShippingCostAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetFbtShippingCostAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.FbtShippingCostAmount) {
        return nil, false
    }
    return o.FbtShippingCostAmount, true
}

// HasFbtShippingCostAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasFbtShippingCostAmount() bool {
    if o != nil && !utils.IsNil(o.FbtShippingCostAmount) {
        return true
    }

    return false
}

// SetFbtShippingCostAmount gets a reference to the given string and assigns it to the FbtShippingCostAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetFbtShippingCostAmount(v string) {
    o.FbtShippingCostAmount = &v
}

// GetPlatformShippingFeeDiscountAmount returns the PlatformShippingFeeDiscountAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetPlatformShippingFeeDiscountAmount() string {
    if o == nil || utils.IsNil(o.PlatformShippingFeeDiscountAmount) {
        var ret string
        return ret
    }
    return *o.PlatformShippingFeeDiscountAmount
}

// GetPlatformShippingFeeDiscountAmountOk returns a tuple with the PlatformShippingFeeDiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetPlatformShippingFeeDiscountAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.PlatformShippingFeeDiscountAmount) {
        return nil, false
    }
    return o.PlatformShippingFeeDiscountAmount, true
}

// HasPlatformShippingFeeDiscountAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasPlatformShippingFeeDiscountAmount() bool {
    if o != nil && !utils.IsNil(o.PlatformShippingFeeDiscountAmount) {
        return true
    }

    return false
}

// SetPlatformShippingFeeDiscountAmount gets a reference to the given string and assigns it to the PlatformShippingFeeDiscountAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetPlatformShippingFeeDiscountAmount(v string) {
    o.PlatformShippingFeeDiscountAmount = &v
}

// GetPromoShippingIncentiveAmount returns the PromoShippingIncentiveAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetPromoShippingIncentiveAmount() string {
    if o == nil || utils.IsNil(o.PromoShippingIncentiveAmount) {
        var ret string
        return ret
    }
    return *o.PromoShippingIncentiveAmount
}

// GetPromoShippingIncentiveAmountOk returns a tuple with the PromoShippingIncentiveAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetPromoShippingIncentiveAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.PromoShippingIncentiveAmount) {
        return nil, false
    }
    return o.PromoShippingIncentiveAmount, true
}

// HasPromoShippingIncentiveAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasPromoShippingIncentiveAmount() bool {
    if o != nil && !utils.IsNil(o.PromoShippingIncentiveAmount) {
        return true
    }

    return false
}

// SetPromoShippingIncentiveAmount gets a reference to the given string and assigns it to the PromoShippingIncentiveAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetPromoShippingIncentiveAmount(v string) {
    o.PromoShippingIncentiveAmount = &v
}

// GetRefundCustomerShippingFee returns the RefundCustomerShippingFee field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetRefundCustomerShippingFee() string {
    if o == nil || utils.IsNil(o.RefundCustomerShippingFee) {
        var ret string
        return ret
    }
    return *o.RefundCustomerShippingFee
}

// GetRefundCustomerShippingFeeOk returns a tuple with the RefundCustomerShippingFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetRefundCustomerShippingFeeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RefundCustomerShippingFee) {
        return nil, false
    }
    return o.RefundCustomerShippingFee, true
}

// HasRefundCustomerShippingFee returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasRefundCustomerShippingFee() bool {
    if o != nil && !utils.IsNil(o.RefundCustomerShippingFee) {
        return true
    }

    return false
}

// SetRefundCustomerShippingFee gets a reference to the given string and assigns it to the RefundCustomerShippingFee field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetRefundCustomerShippingFee(v string) {
    o.RefundCustomerShippingFee = &v
}

// GetRefundedCustomerShippingFeeAmount returns the RefundedCustomerShippingFeeAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetRefundedCustomerShippingFeeAmount() string {
    if o == nil || utils.IsNil(o.RefundedCustomerShippingFeeAmount) {
        var ret string
        return ret
    }
    return *o.RefundedCustomerShippingFeeAmount
}

// GetRefundedCustomerShippingFeeAmountOk returns a tuple with the RefundedCustomerShippingFeeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetRefundedCustomerShippingFeeAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RefundedCustomerShippingFeeAmount) {
        return nil, false
    }
    return o.RefundedCustomerShippingFeeAmount, true
}

// HasRefundedCustomerShippingFeeAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasRefundedCustomerShippingFeeAmount() bool {
    if o != nil && !utils.IsNil(o.RefundedCustomerShippingFeeAmount) {
        return true
    }

    return false
}

// SetRefundedCustomerShippingFeeAmount gets a reference to the given string and assigns it to the RefundedCustomerShippingFeeAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetRefundedCustomerShippingFeeAmount(v string) {
    o.RefundedCustomerShippingFeeAmount = &v
}

// GetReturnRefundSubsidyAmount returns the ReturnRefundSubsidyAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetReturnRefundSubsidyAmount() string {
    if o == nil || utils.IsNil(o.ReturnRefundSubsidyAmount) {
        var ret string
        return ret
    }
    return *o.ReturnRefundSubsidyAmount
}

// GetReturnRefundSubsidyAmountOk returns a tuple with the ReturnRefundSubsidyAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetReturnRefundSubsidyAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ReturnRefundSubsidyAmount) {
        return nil, false
    }
    return o.ReturnRefundSubsidyAmount, true
}

// HasReturnRefundSubsidyAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasReturnRefundSubsidyAmount() bool {
    if o != nil && !utils.IsNil(o.ReturnRefundSubsidyAmount) {
        return true
    }

    return false
}

// SetReturnRefundSubsidyAmount gets a reference to the given string and assigns it to the ReturnRefundSubsidyAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetReturnRefundSubsidyAmount(v string) {
    o.ReturnRefundSubsidyAmount = &v
}

// GetSellerShippingFeeDiscountAmount returns the SellerShippingFeeDiscountAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetSellerShippingFeeDiscountAmount() string {
    if o == nil || utils.IsNil(o.SellerShippingFeeDiscountAmount) {
        var ret string
        return ret
    }
    return *o.SellerShippingFeeDiscountAmount
}

// GetSellerShippingFeeDiscountAmountOk returns a tuple with the SellerShippingFeeDiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetSellerShippingFeeDiscountAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerShippingFeeDiscountAmount) {
        return nil, false
    }
    return o.SellerShippingFeeDiscountAmount, true
}

// HasSellerShippingFeeDiscountAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasSellerShippingFeeDiscountAmount() bool {
    if o != nil && !utils.IsNil(o.SellerShippingFeeDiscountAmount) {
        return true
    }

    return false
}

// SetSellerShippingFeeDiscountAmount gets a reference to the given string and assigns it to the SellerShippingFeeDiscountAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetSellerShippingFeeDiscountAmount(v string) {
    o.SellerShippingFeeDiscountAmount = &v
}

// GetShippingFeeSubsidyAmount returns the ShippingFeeSubsidyAmount field value if set, zero value otherwise.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetShippingFeeSubsidyAmount() string {
    if o == nil || utils.IsNil(o.ShippingFeeSubsidyAmount) {
        var ret string
        return ret
    }
    return *o.ShippingFeeSubsidyAmount
}

// GetShippingFeeSubsidyAmountOk returns a tuple with the ShippingFeeSubsidyAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) GetShippingFeeSubsidyAmountOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ShippingFeeSubsidyAmount) {
        return nil, false
    }
    return o.ShippingFeeSubsidyAmount, true
}

// HasShippingFeeSubsidyAmount returns a boolean if a field has been set.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) HasShippingFeeSubsidyAmount() bool {
    if o != nil && !utils.IsNil(o.ShippingFeeSubsidyAmount) {
        return true
    }

    return false
}

// SetShippingFeeSubsidyAmount gets a reference to the given string and assigns it to the ShippingFeeSubsidyAmount field.
func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) SetShippingFeeSubsidyAmount(v string) {
    o.ShippingFeeSubsidyAmount = &v
}

func (o Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.CustomerShippingFee) {
        toSerialize["customer_shipping_fee"] = o.CustomerShippingFee
    }
    if !utils.IsNil(o.CustomerShippingFeeOffsetAmount) {
        toSerialize["customer_shipping_fee_offset_amount"] = o.CustomerShippingFeeOffsetAmount
    }
    if !utils.IsNil(o.FbmShippingCostAmount) {
        toSerialize["fbm_shipping_cost_amount"] = o.FbmShippingCostAmount
    }
    if !utils.IsNil(o.FbtFulfillmentFeeAmount) {
        toSerialize["fbt_fulfillment_fee_amount"] = o.FbtFulfillmentFeeAmount
    }
    if !utils.IsNil(o.FbtFulfillmentFeeReimbursementAmount) {
        toSerialize["fbt_fulfillment_fee_reimbursement_amount"] = o.FbtFulfillmentFeeReimbursementAmount
    }
    if !utils.IsNil(o.FbtShippingCostAmount) {
        toSerialize["fbt_shipping_cost_amount"] = o.FbtShippingCostAmount
    }
    if !utils.IsNil(o.PlatformShippingFeeDiscountAmount) {
        toSerialize["platform_shipping_fee_discount_amount"] = o.PlatformShippingFeeDiscountAmount
    }
    if !utils.IsNil(o.PromoShippingIncentiveAmount) {
        toSerialize["promo_shipping_incentive_amount"] = o.PromoShippingIncentiveAmount
    }
    if !utils.IsNil(o.RefundCustomerShippingFee) {
        toSerialize["refund_customer_shipping_fee"] = o.RefundCustomerShippingFee
    }
    if !utils.IsNil(o.RefundedCustomerShippingFeeAmount) {
        toSerialize["refunded_customer_shipping_fee_amount"] = o.RefundedCustomerShippingFeeAmount
    }
    if !utils.IsNil(o.ReturnRefundSubsidyAmount) {
        toSerialize["return_refund_subsidy_amount"] = o.ReturnRefundSubsidyAmount
    }
    if !utils.IsNil(o.SellerShippingFeeDiscountAmount) {
        toSerialize["seller_shipping_fee_discount_amount"] = o.SellerShippingFeeDiscountAmount
    }
    if !utils.IsNil(o.ShippingFeeSubsidyAmount) {
        toSerialize["shipping_fee_subsidy_amount"] = o.ShippingFeeSubsidyAmount
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) UnmarshalJSON(data []byte) (err error) {
    varFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent := _Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent{}

    err = json.Unmarshal(data, &varFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent)

    if err != nil {
        return err
    }

    *o = Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent(varFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "customer_shipping_fee")
        delete(additionalProperties, "customer_shipping_fee_offset_amount")
        delete(additionalProperties, "fbm_shipping_cost_amount")
        delete(additionalProperties, "fbt_fulfillment_fee_amount")
        delete(additionalProperties, "fbt_fulfillment_fee_reimbursement_amount")
        delete(additionalProperties, "fbt_shipping_cost_amount")
        delete(additionalProperties, "platform_shipping_fee_discount_amount")
        delete(additionalProperties, "promo_shipping_incentive_amount")
        delete(additionalProperties, "refund_customer_shipping_fee")
        delete(additionalProperties, "refunded_customer_shipping_fee_amount")
        delete(additionalProperties, "return_refund_subsidy_amount")
        delete(additionalProperties, "seller_shipping_fee_discount_amount")
        delete(additionalProperties, "shipping_fee_subsidy_amount")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent struct {
	value *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent
	isSet bool
}

func (v NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) Get() *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent {
	return v.value
}

func (v *NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) Set(val *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) {
	v.value = val
	v.isSet = true
}

func (v NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) IsSet() bool {
	return v.isSet
}

func (v *NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent(val *Finance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) *NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent {
	return &NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent{value: val, isSet: true}
}

func (v NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinance202501GetTransactionsbyStatementResponseDataTransactionsShippingCostBreakdownSupplementaryComponent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


