/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics_v202508

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance{}

// Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance struct for Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance
type Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance struct {
    // Average concurrent users
    Acu *int64 `json:"acu,omitempty"`
    // The average time each user spent watching LIVEs. Total viewing time divided by number of views, in seconds.
    AvgViewingDuration *string `json:"avg_viewing_duration,omitempty"`
    // The percentage of viewers who clicked on product links after seeing them in this LIVE. Number of clicks divided by the number of views, multiplied by 100.
    ClickThroughRate *string `json:"click_through_rate,omitempty"`
    // Number of comments on the LIVE video posted during the selected period.
    Comments *int64 `json:"comments,omitempty"`
    // The number of likes a LIVE video received during the selected time period.
    Likes *int64 `json:"likes,omitempty"`
    // The number of viewers who followed creators from the video during the selected period.
    NewFollowers *int64 `json:"new_followers,omitempty"`
    // Peak concurrent users
    Pcu *int64 `json:"pcu,omitempty"`
    // Number of product clicks during the LIVE video posted during the selected period, including clicks on product lists and product cards.
    ProductClicks *int64 `json:"product_clicks,omitempty"`
    // Number of product impressions during the LIVE video posted during the selected period, including product lists and product cards
    ProductImpressions *int64 `json:"product_impressions,omitempty"`
    // Number of times the LIVE video posted during the selected period were shared.
    Shares *int64 `json:"shares,omitempty"`
    // Number of unique viewers of the LIVE video posted during the selected period.
    Viewers *int64 `json:"viewers,omitempty"`
    // Number of views for the LIVE video posted during the selected period.
    Views *int64 `json:"views,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance

// NewAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance instantiates a new Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance() *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance {
    this := Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance{}
    return &this
}

// NewAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformanceWithDefaults instantiates a new Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformanceWithDefaults() *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance {
    this := Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance{}
    return &this
}

// GetAcu returns the Acu field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetAcu() int64 {
    if o == nil || utils.IsNil(o.Acu) {
        var ret int64
        return ret
    }
    return *o.Acu
}

// GetAcuOk returns a tuple with the Acu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetAcuOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Acu) {
        return nil, false
    }
    return o.Acu, true
}

// HasAcu returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasAcu() bool {
    if o != nil && !utils.IsNil(o.Acu) {
        return true
    }

    return false
}

// SetAcu gets a reference to the given int64 and assigns it to the Acu field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetAcu(v int64) {
    o.Acu = &v
}

// GetAvgViewingDuration returns the AvgViewingDuration field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetAvgViewingDuration() string {
    if o == nil || utils.IsNil(o.AvgViewingDuration) {
        var ret string
        return ret
    }
    return *o.AvgViewingDuration
}

// GetAvgViewingDurationOk returns a tuple with the AvgViewingDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetAvgViewingDurationOk() (*string, bool) {
    if o == nil || utils.IsNil(o.AvgViewingDuration) {
        return nil, false
    }
    return o.AvgViewingDuration, true
}

// HasAvgViewingDuration returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasAvgViewingDuration() bool {
    if o != nil && !utils.IsNil(o.AvgViewingDuration) {
        return true
    }

    return false
}

// SetAvgViewingDuration gets a reference to the given string and assigns it to the AvgViewingDuration field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetAvgViewingDuration(v string) {
    o.AvgViewingDuration = &v
}

// GetClickThroughRate returns the ClickThroughRate field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetClickThroughRate() string {
    if o == nil || utils.IsNil(o.ClickThroughRate) {
        var ret string
        return ret
    }
    return *o.ClickThroughRate
}

// GetClickThroughRateOk returns a tuple with the ClickThroughRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetClickThroughRateOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ClickThroughRate) {
        return nil, false
    }
    return o.ClickThroughRate, true
}

// HasClickThroughRate returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasClickThroughRate() bool {
    if o != nil && !utils.IsNil(o.ClickThroughRate) {
        return true
    }

    return false
}

// SetClickThroughRate gets a reference to the given string and assigns it to the ClickThroughRate field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetClickThroughRate(v string) {
    o.ClickThroughRate = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetComments() int64 {
    if o == nil || utils.IsNil(o.Comments) {
        var ret int64
        return ret
    }
    return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetCommentsOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Comments) {
        return nil, false
    }
    return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasComments() bool {
    if o != nil && !utils.IsNil(o.Comments) {
        return true
    }

    return false
}

// SetComments gets a reference to the given int64 and assigns it to the Comments field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetComments(v int64) {
    o.Comments = &v
}

// GetLikes returns the Likes field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetLikes() int64 {
    if o == nil || utils.IsNil(o.Likes) {
        var ret int64
        return ret
    }
    return *o.Likes
}

// GetLikesOk returns a tuple with the Likes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetLikesOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Likes) {
        return nil, false
    }
    return o.Likes, true
}

// HasLikes returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasLikes() bool {
    if o != nil && !utils.IsNil(o.Likes) {
        return true
    }

    return false
}

// SetLikes gets a reference to the given int64 and assigns it to the Likes field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetLikes(v int64) {
    o.Likes = &v
}

// GetNewFollowers returns the NewFollowers field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetNewFollowers() int64 {
    if o == nil || utils.IsNil(o.NewFollowers) {
        var ret int64
        return ret
    }
    return *o.NewFollowers
}

// GetNewFollowersOk returns a tuple with the NewFollowers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetNewFollowersOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.NewFollowers) {
        return nil, false
    }
    return o.NewFollowers, true
}

// HasNewFollowers returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasNewFollowers() bool {
    if o != nil && !utils.IsNil(o.NewFollowers) {
        return true
    }

    return false
}

// SetNewFollowers gets a reference to the given int64 and assigns it to the NewFollowers field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetNewFollowers(v int64) {
    o.NewFollowers = &v
}

// GetPcu returns the Pcu field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetPcu() int64 {
    if o == nil || utils.IsNil(o.Pcu) {
        var ret int64
        return ret
    }
    return *o.Pcu
}

// GetPcuOk returns a tuple with the Pcu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetPcuOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Pcu) {
        return nil, false
    }
    return o.Pcu, true
}

// HasPcu returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasPcu() bool {
    if o != nil && !utils.IsNil(o.Pcu) {
        return true
    }

    return false
}

// SetPcu gets a reference to the given int64 and assigns it to the Pcu field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetPcu(v int64) {
    o.Pcu = &v
}

// GetProductClicks returns the ProductClicks field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetProductClicks() int64 {
    if o == nil || utils.IsNil(o.ProductClicks) {
        var ret int64
        return ret
    }
    return *o.ProductClicks
}

// GetProductClicksOk returns a tuple with the ProductClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetProductClicksOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.ProductClicks) {
        return nil, false
    }
    return o.ProductClicks, true
}

// HasProductClicks returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasProductClicks() bool {
    if o != nil && !utils.IsNil(o.ProductClicks) {
        return true
    }

    return false
}

// SetProductClicks gets a reference to the given int64 and assigns it to the ProductClicks field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetProductClicks(v int64) {
    o.ProductClicks = &v
}

// GetProductImpressions returns the ProductImpressions field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetProductImpressions() int64 {
    if o == nil || utils.IsNil(o.ProductImpressions) {
        var ret int64
        return ret
    }
    return *o.ProductImpressions
}

// GetProductImpressionsOk returns a tuple with the ProductImpressions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetProductImpressionsOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.ProductImpressions) {
        return nil, false
    }
    return o.ProductImpressions, true
}

// HasProductImpressions returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasProductImpressions() bool {
    if o != nil && !utils.IsNil(o.ProductImpressions) {
        return true
    }

    return false
}

// SetProductImpressions gets a reference to the given int64 and assigns it to the ProductImpressions field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetProductImpressions(v int64) {
    o.ProductImpressions = &v
}

// GetShares returns the Shares field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetShares() int64 {
    if o == nil || utils.IsNil(o.Shares) {
        var ret int64
        return ret
    }
    return *o.Shares
}

// GetSharesOk returns a tuple with the Shares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetSharesOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Shares) {
        return nil, false
    }
    return o.Shares, true
}

// HasShares returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasShares() bool {
    if o != nil && !utils.IsNil(o.Shares) {
        return true
    }

    return false
}

// SetShares gets a reference to the given int64 and assigns it to the Shares field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetShares(v int64) {
    o.Shares = &v
}

// GetViewers returns the Viewers field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetViewers() int64 {
    if o == nil || utils.IsNil(o.Viewers) {
        var ret int64
        return ret
    }
    return *o.Viewers
}

// GetViewersOk returns a tuple with the Viewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetViewersOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Viewers) {
        return nil, false
    }
    return o.Viewers, true
}

// HasViewers returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasViewers() bool {
    if o != nil && !utils.IsNil(o.Viewers) {
        return true
    }

    return false
}

// SetViewers gets a reference to the given int64 and assigns it to the Viewers field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetViewers(v int64) {
    o.Viewers = &v
}

// GetViews returns the Views field value if set, zero value otherwise.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetViews() int64 {
    if o == nil || utils.IsNil(o.Views) {
        var ret int64
        return ret
    }
    return *o.Views
}

// GetViewsOk returns a tuple with the Views field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) GetViewsOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Views) {
        return nil, false
    }
    return o.Views, true
}

// HasViews returns a boolean if a field has been set.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) HasViews() bool {
    if o != nil && !utils.IsNil(o.Views) {
        return true
    }

    return false
}

// SetViews gets a reference to the given int64 and assigns it to the Views field.
func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) SetViews(v int64) {
    o.Views = &v
}

func (o Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Acu) {
        toSerialize["acu"] = o.Acu
    }
    if !utils.IsNil(o.AvgViewingDuration) {
        toSerialize["avg_viewing_duration"] = o.AvgViewingDuration
    }
    if !utils.IsNil(o.ClickThroughRate) {
        toSerialize["click_through_rate"] = o.ClickThroughRate
    }
    if !utils.IsNil(o.Comments) {
        toSerialize["comments"] = o.Comments
    }
    if !utils.IsNil(o.Likes) {
        toSerialize["likes"] = o.Likes
    }
    if !utils.IsNil(o.NewFollowers) {
        toSerialize["new_followers"] = o.NewFollowers
    }
    if !utils.IsNil(o.Pcu) {
        toSerialize["pcu"] = o.Pcu
    }
    if !utils.IsNil(o.ProductClicks) {
        toSerialize["product_clicks"] = o.ProductClicks
    }
    if !utils.IsNil(o.ProductImpressions) {
        toSerialize["product_impressions"] = o.ProductImpressions
    }
    if !utils.IsNil(o.Shares) {
        toSerialize["shares"] = o.Shares
    }
    if !utils.IsNil(o.Viewers) {
        toSerialize["viewers"] = o.Viewers
    }
    if !utils.IsNil(o.Views) {
        toSerialize["views"] = o.Views
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) UnmarshalJSON(data []byte) (err error) {
    varAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance := _Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance{}

    err = json.Unmarshal(data, &varAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance)

    if err != nil {
        return err
    }

    *o = Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance(varAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "acu")
        delete(additionalProperties, "avg_viewing_duration")
        delete(additionalProperties, "click_through_rate")
        delete(additionalProperties, "comments")
        delete(additionalProperties, "likes")
        delete(additionalProperties, "new_followers")
        delete(additionalProperties, "pcu")
        delete(additionalProperties, "product_clicks")
        delete(additionalProperties, "product_impressions")
        delete(additionalProperties, "shares")
        delete(additionalProperties, "viewers")
        delete(additionalProperties, "views")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance struct {
	value *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance
	isSet bool
}

func (v NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) Get() *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance {
	return v.value
}

func (v *NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) Set(val *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance(val *Analytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) *NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance {
	return &NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance{value: val, isSet: true}
}

func (v NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalytics202508GetShopLIVEPerformanceListResponseDataLiveStreamSessionsInteractionPerformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


