/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillment_v202508

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Fulfillment202508TTSTrackingValidationResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Fulfillment202508TTSTrackingValidationResponseData{}

// Fulfillment202508TTSTrackingValidationResponseData struct for Fulfillment202508TTSTrackingValidationResponseData
type Fulfillment202508TTSTrackingValidationResponseData struct {
    // A flag to determine whether the package is TikTok Collections
    IsTiktokCollection *bool `json:"is_tiktok_collection,omitempty"`
    // A flag to determine whether the package is TikTok Shipping
    IsTiktokShipping *bool `json:"is_tiktok_shipping,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Fulfillment202508TTSTrackingValidationResponseData Fulfillment202508TTSTrackingValidationResponseData

// NewFulfillment202508TTSTrackingValidationResponseData instantiates a new Fulfillment202508TTSTrackingValidationResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillment202508TTSTrackingValidationResponseData() *Fulfillment202508TTSTrackingValidationResponseData {
    this := Fulfillment202508TTSTrackingValidationResponseData{}
    return &this
}

// NewFulfillment202508TTSTrackingValidationResponseDataWithDefaults instantiates a new Fulfillment202508TTSTrackingValidationResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillment202508TTSTrackingValidationResponseDataWithDefaults() *Fulfillment202508TTSTrackingValidationResponseData {
    this := Fulfillment202508TTSTrackingValidationResponseData{}
    return &this
}

// GetIsTiktokCollection returns the IsTiktokCollection field value if set, zero value otherwise.
func (o *Fulfillment202508TTSTrackingValidationResponseData) GetIsTiktokCollection() bool {
    if o == nil || utils.IsNil(o.IsTiktokCollection) {
        var ret bool
        return ret
    }
    return *o.IsTiktokCollection
}

// GetIsTiktokCollectionOk returns a tuple with the IsTiktokCollection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202508TTSTrackingValidationResponseData) GetIsTiktokCollectionOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.IsTiktokCollection) {
        return nil, false
    }
    return o.IsTiktokCollection, true
}

// HasIsTiktokCollection returns a boolean if a field has been set.
func (o *Fulfillment202508TTSTrackingValidationResponseData) HasIsTiktokCollection() bool {
    if o != nil && !utils.IsNil(o.IsTiktokCollection) {
        return true
    }

    return false
}

// SetIsTiktokCollection gets a reference to the given bool and assigns it to the IsTiktokCollection field.
func (o *Fulfillment202508TTSTrackingValidationResponseData) SetIsTiktokCollection(v bool) {
    o.IsTiktokCollection = &v
}

// GetIsTiktokShipping returns the IsTiktokShipping field value if set, zero value otherwise.
func (o *Fulfillment202508TTSTrackingValidationResponseData) GetIsTiktokShipping() bool {
    if o == nil || utils.IsNil(o.IsTiktokShipping) {
        var ret bool
        return ret
    }
    return *o.IsTiktokShipping
}

// GetIsTiktokShippingOk returns a tuple with the IsTiktokShipping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202508TTSTrackingValidationResponseData) GetIsTiktokShippingOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.IsTiktokShipping) {
        return nil, false
    }
    return o.IsTiktokShipping, true
}

// HasIsTiktokShipping returns a boolean if a field has been set.
func (o *Fulfillment202508TTSTrackingValidationResponseData) HasIsTiktokShipping() bool {
    if o != nil && !utils.IsNil(o.IsTiktokShipping) {
        return true
    }

    return false
}

// SetIsTiktokShipping gets a reference to the given bool and assigns it to the IsTiktokShipping field.
func (o *Fulfillment202508TTSTrackingValidationResponseData) SetIsTiktokShipping(v bool) {
    o.IsTiktokShipping = &v
}

func (o Fulfillment202508TTSTrackingValidationResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Fulfillment202508TTSTrackingValidationResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.IsTiktokCollection) {
        toSerialize["is_tiktok_collection"] = o.IsTiktokCollection
    }
    if !utils.IsNil(o.IsTiktokShipping) {
        toSerialize["is_tiktok_shipping"] = o.IsTiktokShipping
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Fulfillment202508TTSTrackingValidationResponseData) UnmarshalJSON(data []byte) (err error) {
    varFulfillment202508TTSTrackingValidationResponseData := _Fulfillment202508TTSTrackingValidationResponseData{}

    err = json.Unmarshal(data, &varFulfillment202508TTSTrackingValidationResponseData)

    if err != nil {
        return err
    }

    *o = Fulfillment202508TTSTrackingValidationResponseData(varFulfillment202508TTSTrackingValidationResponseData)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "is_tiktok_collection")
        delete(additionalProperties, "is_tiktok_shipping")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableFulfillment202508TTSTrackingValidationResponseData struct {
	value *Fulfillment202508TTSTrackingValidationResponseData
	isSet bool
}

func (v NullableFulfillment202508TTSTrackingValidationResponseData) Get() *Fulfillment202508TTSTrackingValidationResponseData {
	return v.value
}

func (v *NullableFulfillment202508TTSTrackingValidationResponseData) Set(val *Fulfillment202508TTSTrackingValidationResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillment202508TTSTrackingValidationResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillment202508TTSTrackingValidationResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillment202508TTSTrackingValidationResponseData(val *Fulfillment202508TTSTrackingValidationResponseData) *NullableFulfillment202508TTSTrackingValidationResponseData {
	return &NullableFulfillment202508TTSTrackingValidationResponseData{value: val, isSet: true}
}

func (v NullableFulfillment202508TTSTrackingValidationResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillment202508TTSTrackingValidationResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


