/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202507

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202507ReplicateProductResponseDataErrorsDetail type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202507ReplicateProductResponseDataErrorsDetail{}

// Product202507ReplicateProductResponseDataErrorsDetail struct for Product202507ReplicateProductResponseDataErrorsDetail
type Product202507ReplicateProductResponseDataErrorsDetail struct {
    // The target region where the error occurred.
    Region *string `json:"region,omitempty"`
    AdditionalProperties map[string]interface{}
}

type _Product202507ReplicateProductResponseDataErrorsDetail Product202507ReplicateProductResponseDataErrorsDetail

// NewProduct202507ReplicateProductResponseDataErrorsDetail instantiates a new Product202507ReplicateProductResponseDataErrorsDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202507ReplicateProductResponseDataErrorsDetail() *Product202507ReplicateProductResponseDataErrorsDetail {
    this := Product202507ReplicateProductResponseDataErrorsDetail{}
    return &this
}

// NewProduct202507ReplicateProductResponseDataErrorsDetailWithDefaults instantiates a new Product202507ReplicateProductResponseDataErrorsDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202507ReplicateProductResponseDataErrorsDetailWithDefaults() *Product202507ReplicateProductResponseDataErrorsDetail {
    this := Product202507ReplicateProductResponseDataErrorsDetail{}
    return &this
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *Product202507ReplicateProductResponseDataErrorsDetail) GetRegion() string {
    if o == nil || utils.IsNil(o.Region) {
        var ret string
        return ret
    }
    return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202507ReplicateProductResponseDataErrorsDetail) GetRegionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Region) {
        return nil, false
    }
    return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *Product202507ReplicateProductResponseDataErrorsDetail) HasRegion() bool {
    if o != nil && !utils.IsNil(o.Region) {
        return true
    }

    return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *Product202507ReplicateProductResponseDataErrorsDetail) SetRegion(v string) {
    o.Region = &v
}

func (o Product202507ReplicateProductResponseDataErrorsDetail) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202507ReplicateProductResponseDataErrorsDetail) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Region) {
        toSerialize["region"] = o.Region
    }

    for key, value := range o.AdditionalProperties {
        toSerialize[key] = value
    }

    return toSerialize, nil
}

func (o *Product202507ReplicateProductResponseDataErrorsDetail) UnmarshalJSON(data []byte) (err error) {
    varProduct202507ReplicateProductResponseDataErrorsDetail := _Product202507ReplicateProductResponseDataErrorsDetail{}

    err = json.Unmarshal(data, &varProduct202507ReplicateProductResponseDataErrorsDetail)

    if err != nil {
        return err
    }

    *o = Product202507ReplicateProductResponseDataErrorsDetail(varProduct202507ReplicateProductResponseDataErrorsDetail)

    additionalProperties := make(map[string]interface{})

    if err = json.Unmarshal(data, &additionalProperties); err == nil {
        delete(additionalProperties, "region")
        o.AdditionalProperties = additionalProperties
    }
    return err
}

type NullableProduct202507ReplicateProductResponseDataErrorsDetail struct {
	value *Product202507ReplicateProductResponseDataErrorsDetail
	isSet bool
}

func (v NullableProduct202507ReplicateProductResponseDataErrorsDetail) Get() *Product202507ReplicateProductResponseDataErrorsDetail {
	return v.value
}

func (v *NullableProduct202507ReplicateProductResponseDataErrorsDetail) Set(val *Product202507ReplicateProductResponseDataErrorsDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202507ReplicateProductResponseDataErrorsDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202507ReplicateProductResponseDataErrorsDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202507ReplicateProductResponseDataErrorsDetail(val *Product202507ReplicateProductResponseDataErrorsDetail) *NullableProduct202507ReplicateProductResponseDataErrorsDetail {
	return &NullableProduct202507ReplicateProductResponseDataErrorsDetail{value: val, isSet: true}
}

func (v NullableProduct202507ReplicateProductResponseDataErrorsDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202507ReplicateProductResponseDataErrorsDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


